// Command gencorpus writes the native-bridge candidate vector corpus: the
// protocol/vectors tree of native-bridge-plugins, generated by the Go oracle.
//
//	go run ./bridgeprofile/cmd/gencorpus -out DIR
//
// The output is deterministic; running it twice produces identical bytes.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/unicitynetwork/bft-core/bridgeprofile"
)

func main() {
	out := flag.String("out", "", "directory to write the vector tree into (required)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "gencorpus: -out is required")
		os.Exit(2)
	}
	c, err := bridgeprofile.BuildCorpus()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gencorpus:", err)
		os.Exit(1)
	}
	for path, b := range c.Files {
		p := filepath.Join(*out, path)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "gencorpus:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(p, b, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "gencorpus:", err)
			os.Exit(1)
		}
	}
	fmt.Println("corpus digest", c.Digest())
}
