package evmassign

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// testdata/custody-digests.json is generated by custody itself (unicity-pos-contracts test/p85/CustodyDigests.t.sol, which fails when the
// committed copy is stale): custody's stored exposure digest, key-history digest, exposure ids and per-identity exposure chain for the
// genesis, a primary and a derived recovery assignment. Custody is normative; the root must derive the same words from the frozen
// identity records.

type custodyMember struct {
	ID            uint64   `json:"id"`
	Generation    uint64   `json:"generation"`
	Weight        uint64   `json:"weight"`
	OperatorPayee string   `json:"operatorPayee"`
	RootKeyHash   string   `json:"rootKeyHash"`
	EVMKeyHash    string   `json:"evmKeyHash"`
	LotIDs        []uint64 `json:"lotIds"`
	ExposureID    string   `json:"exposureId"`
}

type custodyAssignment struct {
	AssignmentID   string          `json:"assignmentId"`
	ExposureDigest string          `json:"exposureDigest"`
	KeyDigest      string          `json:"keyDigest"`
	Members        []custodyMember `json:"members"`
}

type custodyScenario struct {
	Name        string              `json:"name"`
	Assignments []custodyAssignment `json:"assignments"`
	Chains      []struct {
		ID         uint64 `json:"id"`
		Generation uint64 `json:"generation"`
		Chain      string `json:"chain"`
	} `json:"chains"`
}

type custodyFixture struct {
	Deployment struct {
		NetworkWord string `json:"networkWord"`
		ChainID     uint64 `json:"chainId"`
		Custody     string `json:"custody"`
	} `json:"deployment"`
	Scenarios []custodyScenario `json:"scenarios"`
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
	require.NoError(t, err)
	return b
}

func b32(t *testing.T, s string) (a [32]byte) {
	t.Helper()
	copy(a[:], unhex(t, s))
	return a
}

func TestCustodyDigestsReproduceCustodysOwn(t *testing.T) {
	raw, err := os.ReadFile("testdata/custody-digests.json")
	require.NoError(t, err)
	var fx custodyFixture
	require.NoError(t, json.Unmarshal(raw, &fx))
	require.Len(t, fx.Scenarios, 3)
	var d Deployment
	d.NetworkWord = b32(t, fx.Deployment.NetworkWord)
	cid := new(big.Int).SetUint64(fx.Deployment.ChainID).FillBytes(make([]byte, 32))
	copy(d.ChainID[:], cid)
	copy(d.Custody[:], unhex(t, fx.Deployment.Custody))

	for _, sc := range fx.Scenarios {
		chains := map[uint64][32]byte{} // creation-ordered exposure chain per identity, assignments in the order custody created them
		for _, a := range sc.Assignments {
			asg := b32(t, a.AssignmentID)
			var ids []Identity
			var uids []uint64
			var rootHashes, evmHashes [][32]byte
			for _, m := range a.Members {
				sid := make([]byte, 32)
				copy(sid[24:], w64(m.ID)[24:])
				ld := LotsDigest(m.LotIDs)
				ids = append(ids, Identity{StakingID: sid, Generation: m.Generation, Weight: m.Weight, OperatorPayee: unhex(t, m.OperatorPayee), ExposureDigest: ld[:]})
				uids = append(uids, m.ID)
				rootHashes = append(rootHashes, b32(t, m.RootKeyHash))
				evmHashes = append(evmHashes, b32(t, m.EVMKeyHash))
				eid := ExposureID(d, asg, m.ID)
				require.Equal(t, b32(t, m.ExposureID), eid, "%s: exposure id of %d", sc.Name, m.ID)
				chains[m.ID] = ExposureChainStep(chains[m.ID], eid)
			}
			ed, err := AssignmentExposureDigest(d, asg, ids)
			require.NoError(t, err)
			require.Equal(t, b32(t, a.ExposureDigest), ed, "%s: exposure digest of %s", sc.Name, a.AssignmentID)
			kd, err := KeyHistoryDigestFromHashes(uids, rootHashes, evmHashes)
			require.NoError(t, err)
			require.Equal(t, b32(t, a.KeyDigest), kd, "%s: key-history digest of %s", sc.Name, a.AssignmentID)
		}
		for _, c := range sc.Chains {
			require.Equal(t, b32(t, c.Chain), chains[c.ID], "%s: exposure chain of identity %d", sc.Name, c.ID)
		}
	}
}
