package evmassign

import (
	"bytes"
	"errors"
	"fmt"
	"math/big"

	ethcrypto "github.com/ethereum/go-ethereum/crypto"
)

// The proof slots of a published primary candidate (unicity-pos-contracts ElectionPolicy.Publication) and the words the root recomputes
// from a candidate's identity records and possession proofs to bind the two. The EVM never sees the candidate's CBOR or its
// partition description: it commits to the frozen identity records through custody's own exposure and key-history digests, to the
// possession proofs through an EVM-native digest each member's EVM key signs, and to the recovery slate K through the incumbent
// assignment's digests. The root derives every one of those words from the candidate and requires the proven slots to equal them.
// test/p85/fixtures/publication.json (generated by the contracts) is the shared fixture.

var (
	primaryAssignmentDomain = ethcrypto.Keccak256Hash([]byte("unicity.p85.primary-assignment"))
	evmPoPDomain            = ethcrypto.Keccak256Hash([]byte("unicity.p85.assignment-pop"))
	popSetDomain            = ethcrypto.Keccak256Hash([]byte("unicity.p85.pop-set"))
	primaryDomain           = ethcrypto.Keccak256Hash([]byte("unicity.p85.primary-commitment"))
	kCommitDomain           = ethcrypto.Keccak256Hash([]byte("unicity.p85.recovery-authorization"))
)

var (
	// ErrPrimaryProof is the root of every rejection of a primary candidate's EVM proof.
	ErrPrimaryProof = errors.New("evmassign: primary candidate proof")
	// ErrNotPublished reports a result that is not published, or whose possession proofs are not all stored.
	ErrNotPublished = errors.Join(ErrPrimaryProof, errors.New("result is not published"))
	// ErrStaleResult reports a result that is no longer the open reservation over the last acknowledged assignment.
	ErrStaleResult = errors.Join(ErrPrimaryProof, errors.New("result is not the open reservation over the last acknowledged assignment"))
	// ErrPrimaryBinding reports a candidate that does not name the proven result, assignment, snapshot, policies or deployment.
	ErrPrimaryBinding = errors.Join(ErrPrimaryProof, errors.New("candidate is not bound to the proven result"))
	// ErrPrimaryIdentities reports identity records that are not the ones the proven primary commitment covers.
	ErrPrimaryIdentities = errors.Join(ErrPrimaryProof, errors.New("identity records differ from the proven primary commitment"))
	// ErrPrimaryPoP reports a missing, misplaced or invalid EVM possession proof, or a proof set the proven slot does not commit to.
	ErrPrimaryPoP = errors.Join(ErrPrimaryProof, errors.New("possession proofs differ from the proven slots"))
	// ErrCoverageLost reports a result a member of which lost its coverage after the snapshot: a primary that was published must not pass
	// Prepare after a slash or an exclusion. A retirement requested after the snapshot is NOT a loss (the exposure lots stay encumbered
	// until their references close, so the committed weight is still backed): the proven word is the same whether or not anyone called
	// reconcileCandidate.
	ErrCoverageLost = errors.Join(ErrPrimaryProof, errors.New("a member lost its coverage after the snapshot"))
	// ErrPrimaryRecovery reports a recovery authorization that is not the one the proven K commitment covers.
	ErrPrimaryRecovery = errors.Join(ErrPrimaryProof, errors.New("recovery authorization differs from the proven K commitment"))
)

// PrimaryFacts are the words the certified Election and custody state at P establish about one result: the fixed proof slots of
// Election.publication(resultID) and the two custody facts that keep the result current.
type PrimaryFacts struct {
	ResultID                [32]byte
	Published               bool
	PopCount                uint32
	Attempt                 uint64
	PrimaryHash             [32]byte
	KCommit                 [32]byte
	Incumbent               [32]byte
	IncumbentExposureDigest [32]byte
	IncumbentKeyDigest      [32]byte
	PolicyDigest            [32]byte
	ContractsDigest         [32]byte
	SnapshotDigest          [32]byte
	AssignmentID            [32]byte
	PopSetDigest            [32]byte
	// CoverageLost: the election recorded (event-driven from Evidence, or on demand through reconcileCandidate) that a member fell
	// short of its committed weight. Once set it is never cleared.
	CoverageLost bool
	// Open: the custody session of the result is open and its assignment is still only reserved.
	Open bool
	// IncumbentIsLastAcked: custody's last acknowledged assignment is the incumbent the result replaces, so no other session was
	// installed over it and K is still the committee in force.
	IncumbentIsLastAcked bool
}

// EVMPoP is one member's possession proof for the EVM-side publication: its EVM key and a signature by it over PoPDigest.
type EVMPoP struct {
	_         struct{} `cbor:",toarray"`
	ID        uint64
	EVMKey    []byte
	Signature []byte
}

// ElectionDeployment adds the Election module to the custody deployment.
type ElectionDeployment struct {
	Deployment
	Election [20]byte
}

func w32(b [32]byte) []byte { return b[:] }

// PrimaryAssignmentID is the EVM assignment identifier of an election result.
func PrimaryAssignmentID(resultID [32]byte) [32]byte {
	return keccak(primaryAssignmentDomain[:], resultID[:])
}

// PoPDigest is the digest a member's EVM key signs to prove possession for one frozen result (Election.popDigest).
func PoPDigest(d ElectionDeployment, resultID, assignmentID, snapshot [32]byte, attempt, id, generation uint64, evmKey []byte) [32]byte {
	return keccak(evmPoPDomain[:], d.NetworkWord[:], d.ChainID[:], wAddr(d.Election[:]), resultID[:], assignmentID[:], snapshot[:],
		w64(attempt), w64(id), w64(generation), keccak256Bytes(evmKey))
}

func keccak256Bytes(b []byte) []byte { h := ethcrypto.Keccak256(b); return h }

// PoPSetDigest folds the stored proof hashes (keccak256 of each signature) in ascending identity order.
func PoPSetDigest(ids []uint64, sigs [][]byte) [32]byte {
	d := popSetDomain
	for i, id := range ids {
		h := ethcrypto.Keccak256(sigs[i])
		d = keccak(d[:], w64(id), h)
	}
	return d
}

// PrimaryHash is the commitment finalizeCandidate writes.
func PrimaryHash(d ElectionDeployment, resultID, assignmentID, incumbent, snapshot, exposureDigest, keyDigest, popSet [32]byte, attempt uint64) [32]byte {
	return keccak(primaryDomain[:], d.NetworkWord[:], d.ChainID[:], wAddr(d.Custody[:]), wAddr(d.Election[:]), resultID[:], assignmentID[:],
		incumbent[:], w64(attempt), snapshot[:], exposureDigest[:], keyDigest[:], popSet[:])
}

// KCommit is the mandatory recovery-authorization commitment written when the result is reserved.
func KCommit(d ElectionDeployment, resultID, snapshot, incumbent, incumbentExposure, incumbentKey, policies, contracts [32]byte) [32]byte {
	return keccak(kCommitDomain[:], d.NetworkWord[:], d.ChainID[:], resultID[:], snapshot[:], incumbent[:], incumbentExposure[:], incumbentKey[:],
		policies[:], contracts[:])
}

var secp256k1HalfN = new(big.Int).Rsh(ethcrypto.S256().Params().N, 1)

// verifyEVMSignature requires a canonical 65-byte (r, s, v) low-s signature by key over digest.
func verifyEVMSignature(key, sig []byte, digest [32]byte) bool {
	if len(sig) != 65 || (sig[64] != 27 && sig[64] != 28) {
		return false
	}
	if new(big.Int).SetBytes(sig[32:64]).Cmp(secp256k1HalfN) > 0 {
		return false
	}
	rec := append(append([]byte{}, sig[:64]...), sig[64]-27)
	pub, err := ethcrypto.SigToPub(digest[:], rec)
	return err == nil && bytes.Equal(ethcrypto.CompressPubkey(pub), key)
}

func idsOf(ids []Identity) ([]uint64, error) { return ascendingCustodyIDs(ids) }

// VerifyPrimary is the Prepare-side judgement of a primary candidate against the proven EVM state: the result is published and still the
// open reservation over the last acknowledged assignment; the candidate names that result, its snapshot, policies and deployment; its
// identity records are exactly those the proven primary commitment covers; every member's EVM possession proof is valid and is the set
// the proven slot commits to; and its recovery authorization is exactly the K the proven commitment covers.
func VerifyPrimary(c Candidate, d ElectionDeployment, f PrimaryFacts, pops []EVMPoP) error {
	if c.Kind != KindPrimary || c.Authorization == nil {
		return fmt.Errorf("%w: not a primary candidate", ErrPrimaryBinding)
	}
	if !f.Published || int(f.PopCount) != len(c.Identities) {
		return ErrNotPublished
	}
	if f.CoverageLost {
		return ErrCoverageLost
	}
	if !f.Open || !f.IncumbentIsLastAcked {
		return ErrStaleResult
	}
	a := c.Authorization
	var resultID, snapshot, policies, contracts [32]byte
	if len(a.ResultID) != 32 || len(a.SnapshotDigest) != 32 || len(a.Policies) != 32 || len(a.Contracts) != 32 {
		return fmt.Errorf("%w: authorization field widths", ErrPrimaryBinding)
	}
	copy(resultID[:], a.ResultID)
	copy(snapshot[:], a.SnapshotDigest)
	copy(policies[:], a.Policies)
	copy(contracts[:], a.Contracts)
	if resultID != f.ResultID || snapshot != f.SnapshotDigest || policies != f.PolicyDigest || contracts != f.ContractsDigest ||
		f.AssignmentID != PrimaryAssignmentID(resultID) {
		return ErrPrimaryBinding
	}

	// identity records: custody's own digests over the frozen records
	exposure, err := AssignmentExposureDigest(d.Deployment, f.AssignmentID, c.Identities)
	if err != nil {
		return errors.Join(ErrPrimaryIdentities, err)
	}
	keys, err := KeyHistoryDigest(c.Identities)
	if err != nil {
		return errors.Join(ErrPrimaryIdentities, err)
	}

	// possession proofs, one per member in ascending identity order, by the member's own EVM key
	ids, err := idsOf(c.Identities)
	if err != nil {
		return errors.Join(ErrPrimaryIdentities, err)
	}
	if len(pops) != len(ids) {
		return fmt.Errorf("%w: %d proofs for %d members", ErrPrimaryPoP, len(pops), len(ids))
	}
	sigs := make([][]byte, len(ids))
	for i, id := range c.Identities {
		p := pops[i]
		if p.ID != ids[i] || !bytes.Equal(p.EVMKey, id.EVMKey) {
			return fmt.Errorf("%w: proof %d is not member %d's", ErrPrimaryPoP, i, ids[i])
		}
		digest := PoPDigest(d, resultID, f.AssignmentID, snapshot, f.Attempt, ids[i], id.Generation, id.EVMKey)
		if !verifyEVMSignature(id.EVMKey, p.Signature, digest) {
			return fmt.Errorf("%w: member %d", ErrPrimaryPoP, ids[i])
		}
		sigs[i] = p.Signature
	}
	popSet := PoPSetDigest(ids, sigs)
	if popSet != f.PopSetDigest {
		return fmt.Errorf("%w: the proof set is not the stored one", ErrPrimaryPoP)
	}
	if PrimaryHash(d, resultID, f.AssignmentID, f.Incumbent, snapshot, exposure, keys, popSet, f.Attempt) != f.PrimaryHash {
		return ErrPrimaryIdentities
	}

	// K: exactly the incumbent committee the proven commitment covers
	kExposure, err := AssignmentExposureDigest(d.Deployment, f.Incumbent, a.K)
	if err != nil {
		return errors.Join(ErrPrimaryRecovery, err)
	}
	kKeys, err := KeyHistoryDigest(a.K)
	if err != nil {
		return errors.Join(ErrPrimaryRecovery, err)
	}
	if kExposure != f.IncumbentExposureDigest || kKeys != f.IncumbentKeyDigest ||
		KCommit(d, resultID, snapshot, f.Incumbent, kExposure, kKeys, policies, contracts) != f.KCommit {
		return ErrPrimaryRecovery
	}
	return nil
}
