package evmassign

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"strings"
	"testing"

	ethcrypto "github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/require"
)

// testdata/publication.json is a copy of unicity-pos-contracts test/p85/fixtures/publication.json, generated by ElectionPolicy itself.
type pubFixture struct {
	Deployment struct {
		NetworkWord string `json:"networkWord"`
		ChainID     uint64 `json:"chainId"`
		Custody     string `json:"custody"`
		Election    string `json:"election"`
	} `json:"deployment"`
	ResultID              string `json:"resultId"`
	AssignmentID          string `json:"assignmentId"`
	IncumbentAssignmentID string `json:"incumbentAssignmentId"`
	Attempt               uint64 `json:"attempt"`
	SnapshotDigest        string `json:"snapshotDigest"`
	Identities            []pubIdentity
	IncumbentIdentities   []pubIdentity `json:"incumbentIdentities"`
	Pops                  []struct {
		ID        uint64 `json:"id"`
		EVMKey    string `json:"evmKey"`
		Digest    string `json:"digest"`
		Signature string `json:"signature"`
	} `json:"pops"`
	Expected struct {
		ExposureDigest, KeyDigest, PopSetDigest, PrimaryHash, KCommit, PolicyDigest, ContractsDigest string
		IncumbentExposureDigest, IncumbentKeyDigest                                                  string
	} `json:"expected"`
	Reserved  pubSlots `json:"reserved"`
	Published pubSlots `json:"published"`
}

type pubIdentity struct {
	ID            uint64   `json:"id"`
	Generation    uint64   `json:"generation"`
	Weight        uint64   `json:"weight"`
	OperatorPayee string   `json:"operatorPayee"`
	RootKey       string   `json:"rootKey"`
	EVMKey        string   `json:"evmKey"`
	LotIDs        []uint64 `json:"lotIds"`
}

type pubSlots struct {
	Slots []string `json:"slots"`
	Words []string `json:"words"`
}

func hx(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
	require.NoError(t, err)
	return b
}

func h32(t *testing.T, s string) (out [32]byte) {
	copy(out[:], hx(t, s))
	return out
}

func (f pubFixture) identities(t *testing.T, list []pubIdentity) []Identity {
	out := make([]Identity, len(list))
	for i, x := range list {
		var sid [32]byte
		new(big.Int).SetUint64(x.ID).FillBytes(sid[24:])
		ex := LotsDigest(x.LotIDs)
		out[i] = Identity{
			StakingID: sid[:], Generation: x.Generation, RootNodeID: "root-" + string(rune('a'+i)), RootKey: hx(t, x.RootKey),
			EVMNodeID: "evm-" + string(rune('a'+i)), EVMKey: hx(t, x.EVMKey), Weight: x.Weight, OperatorPayee: hx(t, x.OperatorPayee), ExposureDigest: ex[:],
		}
	}
	return out
}

func loadPub(t *testing.T) (pubFixture, ElectionDeployment) {
	t.Helper()
	raw, err := os.ReadFile("testdata/publication.json")
	require.NoError(t, err)
	var f pubFixture
	require.NoError(t, json.Unmarshal(raw, &f))
	d := ElectionDeployment{Deployment: Deployment{NetworkWord: h32(t, f.Deployment.NetworkWord)}}
	new(big.Int).SetUint64(f.Deployment.ChainID).FillBytes(d.ChainID[:])
	copy(d.Custody[:], hx(t, f.Deployment.Custody))
	copy(d.Election[:], hx(t, f.Deployment.Election))
	return f, d
}

// pubWord reads the proof slot words of the published scenario the way Go will have to derive them: slot i of the publication struct.
func pubWord(t *testing.T, f pubFixture, resultID [32]byte, i uint64) [32]byte {
	t.Helper()
	base := keccak(resultID[:], word(publicationSlot))
	want := slotWord(base, i)
	for n, s := range f.Published.Slots {
		if h32(t, s) == want {
			return h32(t, f.Published.Words[n])
		}
	}
	t.Fatalf("slot %d of the publication is not in the fixture", i)
	return [32]byte{}
}

func word(v uint64) []byte { return new(big.Int).SetUint64(v).FillBytes(make([]byte, 32)) }

func slotWord(slot [32]byte, add uint64) [32]byte {
	n := new(big.Int).SetBytes(slot[:])
	n.Add(n, new(big.Int).SetUint64(add))
	var out [32]byte
	n.FillBytes(out[:])
	return out
}

// publicationSlot is the declared slot of ElectionPolicy._publications (forge inspect ElectionPolicy storageLayout).
const publicationSlot = 16

func factsFromFixture(t *testing.T, f pubFixture) PrimaryFacts {
	t.Helper()
	rid := h32(t, f.ResultID)
	w := func(i uint64) [32]byte { return pubWord(t, f, rid, i) }
	last := w(10)
	return PrimaryFacts{
		ResultID: rid, PrimaryHash: w(0), KCommit: w(1), Incumbent: w(2), IncumbentExposureDigest: w(3), IncumbentKeyDigest: w(4),
		PolicyDigest: w(5), ContractsDigest: w(6), SnapshotDigest: w(7), AssignmentID: w(8), PopSetDigest: w(9),
		Published: last[31] == 1, PopCount: uint32(new(big.Int).SetBytes(last[27:31]).Uint64()), Attempt: new(big.Int).SetBytes(last[19:27]).Uint64(),
		Open: true, IncumbentIsLastAcked: true,
	}
}

func candidateFromFixture(t *testing.T, f pubFixture, facts PrimaryFacts) Candidate {
	t.Helper()
	k := f.identities(t, f.IncumbentIdentities)
	nz := make([]byte, 32)
	nz[0] = 1
	return Candidate{
		Version: CandidateVersion, Kind: KindPrimary, Network: 1, Attempt: 9,
		Identities: f.identities(t, f.Identities),
		Authorization: &Authorization{
			Network: 1, Contracts: facts.ContractsDigest[:], ResultID: facts.ResultID[:], SnapshotDigest: facts.SnapshotDigest[:],
			BaseRootBodyID: nz, BaseAssignmentHash: nz, K: k, ExposureDigest: nz, Policies: facts.PolicyDigest[:],
		},
	}
}

func popsFromFixture(t *testing.T, f pubFixture) []EVMPoP {
	out := make([]EVMPoP, len(f.Pops))
	for i, p := range f.Pops {
		out[i] = EVMPoP{ID: p.ID, EVMKey: hx(t, p.EVMKey), Signature: hx(t, p.Signature)}
	}
	return out
}

func TestPublicationFixtureIsReproduced(t *testing.T) {
	f, d := loadPub(t)
	facts := factsFromFixture(t, f)
	require.True(t, facts.Published)
	require.EqualValues(t, len(f.Identities), facts.PopCount)
	require.Equal(t, f.Attempt, facts.Attempt)
	require.Equal(t, h32(t, f.Expected.PrimaryHash), facts.PrimaryHash)
	require.Equal(t, h32(t, f.Expected.KCommit), facts.KCommit)
	require.Equal(t, h32(t, f.IncumbentAssignmentID), facts.Incumbent)
	require.Equal(t, PrimaryAssignmentID(facts.ResultID), facts.AssignmentID)

	ids := f.identities(t, f.Identities)
	cids, err := ascendingCustodyIDs(ids)
	require.NoError(t, err)
	exposure, err := AssignmentExposureDigest(d.Deployment, facts.AssignmentID, ids)
	require.NoError(t, err)
	require.Equal(t, h32(t, f.Expected.ExposureDigest), exposure)
	keys, err := KeyHistoryDigest(ids)
	require.NoError(t, err)
	require.Equal(t, h32(t, f.Expected.KeyDigest), keys)

	sigs := make([][]byte, len(f.Pops))
	for i, p := range f.Pops {
		sigs[i] = hx(t, p.Signature)
		digest := PoPDigest(d, facts.ResultID, facts.AssignmentID, facts.SnapshotDigest, facts.Attempt, cids[i], ids[i].Generation, ids[i].EVMKey)
		require.Equal(t, h32(t, p.Digest), digest, "member %d", cids[i])
	}
	require.Equal(t, h32(t, f.Expected.PopSetDigest), PoPSetDigest(cids, sigs))
	require.Equal(t, facts.PrimaryHash, PrimaryHash(d, facts.ResultID, facts.AssignmentID, facts.Incumbent, facts.SnapshotDigest, exposure, keys, facts.PopSetDigest, facts.Attempt))
	require.Equal(t, facts.KCommit, KCommit(d, facts.ResultID, facts.SnapshotDigest, facts.Incumbent, facts.IncumbentExposureDigest, facts.IncumbentKeyDigest, facts.PolicyDigest, facts.ContractsDigest))
}

func TestVerifyPrimaryAcceptsThePublishedResult(t *testing.T) {
	f, d := loadPub(t)
	facts := factsFromFixture(t, f)
	require.NoError(t, VerifyPrimary(candidateFromFixture(t, f, facts), d, facts, popsFromFixture(t, f)))
}

// Each case changes exactly one input; the sentinel it must be refused with names the check that catches it.
func TestVerifyPrimaryRefusesEachBreakage(t *testing.T) {
	flip := func(b []byte) []byte { c := append([]byte{}, b...); c[0] ^= 0xff; return c }
	cases := []struct {
		name string
		want error
		mut  func(*Candidate, *PrimaryFacts, *[]EVMPoP, *ElectionDeployment)
	}{
		{"unpublished", ErrNotPublished, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.Published = false }},
		{"missing stored proofs", ErrNotPublished, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.PopCount-- }},
		{"a member lost its coverage after publication", ErrCoverageLost, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.CoverageLost = true }},
		{"a member lost its coverage after publication", ErrCoverageLost, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.CoverageLost = true }},
		{"a lost result that is also no longer open is still reported as lost", ErrCoverageLost, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			f.CoverageLost, f.Open = true, false
		}},
		{"session closed or assignment no longer reserved", ErrStaleResult, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.Open = false }},
		{"another session installed over the incumbent", ErrStaleResult, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			f.IncumbentIsLastAcked = false
		}},
		{"authorization names another result", ErrPrimaryBinding, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.ResultID = flip(c.Authorization.ResultID)
		}},
		{"authorization names another snapshot", ErrPrimaryBinding, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.SnapshotDigest = flip(c.Authorization.SnapshotDigest)
		}},
		{"authorization names other policies", ErrPrimaryBinding, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.Policies = flip(c.Authorization.Policies)
		}},
		{"authorization names another deployment", ErrPrimaryBinding, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.Contracts = flip(c.Authorization.Contracts)
		}},
		{"proven assignment is not the result's", ErrPrimaryBinding, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.AssignmentID[0] ^= 1 }},
		{"a member's weight differs", ErrPrimaryIdentities, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { c.Identities[1].Weight++ }},
		{"a member's payee differs", ErrPrimaryIdentities, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Identities[1].OperatorPayee = flip(c.Identities[1].OperatorPayee)
		}},
		{"a member's lots differ", ErrPrimaryIdentities, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Identities[2].ExposureDigest = flip(c.Identities[2].ExposureDigest)
		}},
		{"a member's root key differs", ErrPrimaryIdentities, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Identities[0].RootKey = flip(c.Identities[0].RootKey)
		}},
		{"the proven primary hash differs", ErrPrimaryIdentities, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.PrimaryHash[0] ^= 1 }},
		{"proof of another member", ErrPrimaryPoP, func(_ *Candidate, _ *PrimaryFacts, p *[]EVMPoP, _ *ElectionDeployment) {
			(*p)[0], (*p)[1] = (*p)[1], (*p)[0]
		}},
		{"a proof is missing", ErrPrimaryPoP, func(_ *Candidate, _ *PrimaryFacts, p *[]EVMPoP, _ *ElectionDeployment) { *p = (*p)[1:] }},
		{"a signature is invalid", ErrPrimaryPoP, func(_ *Candidate, _ *PrimaryFacts, p *[]EVMPoP, _ *ElectionDeployment) {
			(*p)[0].Signature = flip((*p)[0].Signature)
		}},
		{"a signature is high-s", ErrPrimaryPoP, func(_ *Candidate, _ *PrimaryFacts, p *[]EVMPoP, _ *ElectionDeployment) {
			s := new(big.Int).SetBytes((*p)[0].Signature[32:64])
			s.Sub(ethcrypto.S256().Params().N, s)
			sig := append([]byte{}, (*p)[0].Signature...)
			s.FillBytes(sig[32:64])
			sig[64] = 27 + 28 - sig[64]
			(*p)[0].Signature = sig
		}},
		{"the proof set is not the stored one", ErrPrimaryPoP, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.PopSetDigest[0] ^= 1 }},
		{"the possession digest names another election", ErrPrimaryPoP, func(_ *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, d *ElectionDeployment) {
			d.Election[0] ^= 1
		}},
		{"K is not the incumbent committee", ErrPrimaryRecovery, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { c.Authorization.K[0].Weight++ }},
		{"K lots differ", ErrPrimaryRecovery, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.K[1].ExposureDigest = flip(c.Authorization.K[1].ExposureDigest)
		}},
		{"K evm key differs", ErrPrimaryRecovery, func(c *Candidate, _ *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) {
			c.Authorization.K[1].EVMKey = flip(c.Authorization.K[1].EVMKey)
		}},
		{"the proven K commitment differs", ErrPrimaryRecovery, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.KCommit[0] ^= 1 }},
		{"the proven incumbent differs", ErrPrimaryIdentities, func(_ *Candidate, f *PrimaryFacts, _ *[]EVMPoP, _ *ElectionDeployment) { f.Incumbent[0] ^= 1 }},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f, d := loadPub(t)
			facts := factsFromFixture(t, f)
			c := candidateFromFixture(t, f, facts)
			pops := popsFromFixture(t, f)
			tc.mut(&c, &facts, &pops, &d)
			err := VerifyPrimary(c, d, facts, pops)
			require.ErrorIs(t, err, tc.want)
			// isolation: no other sentinel family is the reason
			for _, other := range []error{ErrNotPublished, ErrStaleResult, ErrCoverageLost, ErrPrimaryBinding, ErrPrimaryIdentities, ErrPrimaryPoP, ErrPrimaryRecovery} {
				if other != tc.want {
					require.NotErrorIs(t, err, other)
				}
			}
		})
	}
}

func TestVerifyPrimaryRefusesARecoveryCandidate(t *testing.T) {
	f, d := loadPub(t)
	facts := factsFromFixture(t, f)
	c := candidateFromFixture(t, f, facts)
	c.Kind = KindRecovery
	require.ErrorIs(t, VerifyPrimary(c, d, facts, popsFromFixture(t, f)), ErrPrimaryBinding)
}
