package evmassign

import (
	"bytes"
	"encoding/json"
	"os"
	"strconv"
	"testing"

	"github.com/stretchr/testify/require"
)

type quantVectors struct {
	B     uint64 `json:"b"`
	Cases []struct {
		Name  string   `json:"name"`
		B     uint64   `json:"b"`
		X     []string `json:"x"`
		Q     []string `json:"q"`
		S     string   `json:"s"`
		Error bool     `json:"error"`
	} `json:"cases"`
}

func u64s(t *testing.T, in []string) []uint64 {
	out := make([]uint64, len(in))
	for i, s := range in {
		v, err := strconv.ParseUint(s, 10, 64)
		require.NoError(t, err)
		out[i] = v
	}
	return out
}

// The vectors are generated by unicity-pos-contracts tools/quant_vectors.py with exact integer arithmetic; Quantize.sol and ureth's quant.rs
// are checked against the same file.
func TestQuantizeReproducesTheSharedVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/quant-vectors.json")
	require.NoError(t, err)
	var v quantVectors
	require.NoError(t, json.Unmarshal(raw, &v))
	require.EqualValues(t, 65536, v.B)
	require.Greater(t, len(v.Cases), 30)
	for _, c := range v.Cases {
		x := u64s(t, c.X)
		q, s, err := Quantize(x, c.B)
		if c.Error {
			require.ErrorIs(t, err, ErrQuantize, c.Name)
			continue
		}
		require.NoError(t, err, c.Name)
		require.Equal(t, u64s(t, c.Q), q, c.Name)
		require.Equal(t, u64s(t, []string{c.S})[0], s, c.Name)
	}
}

func TestQuantizeInvariants(t *testing.T) {
	const b = 65536
	for seed := uint64(1); seed <= 300; seed++ {
		n := 1 + int(seed*7919%100)
		x := make([]uint64, n)
		var total uint64
		mag := uint64(1) << (1 + seed%40)
		for i := range x {
			x[i] = (seed*2654435761+uint64(i)*40503)%mag + 1
			total += x[i]
		}
		q, _, err := Quantize(x, b)
		require.NoError(t, err)
		var sum uint64
		for i := range q {
			require.GreaterOrEqual(t, q[i], uint64(1))
			require.LessOrEqual(t, q[i], x[i])
			sum += q[i]
			for j := range q {
				if x[i] >= x[j] {
					require.GreaterOrEqual(t, q[i], q[j], "the raw order is preserved weakly")
				}
			}
			if total <= b {
				require.Equal(t, x[i], q[i])
			}
		}
		require.LessOrEqual(t, sum, uint64(b))
	}
}

// Each refusal differs from a valid input in one thing.
func TestQuantizeRefusals(t *testing.T) {
	_, _, err := Quantize([]uint64{1, 2, 3}, 100)
	require.NoError(t, err)
	for name, x := range map[string][]uint64{"empty": nil, "a zero": {1, 0, 3}, "overflow": {^uint64(0), 1}} {
		_, _, err := Quantize(x, 100)
		require.ErrorIs(t, err, ErrQuantize, name)
	}
	_, _, err = Quantize([]uint64{1, 1}, 2)
	require.ErrorIs(t, err, ErrQuantize, "n >= B")
}

func recordsOf(raw ...uint64) []Identity {
	q, _, err := Quantize(raw, 65536)
	if err != nil {
		panic(err)
	}
	out := make([]Identity, len(raw))
	for i := range raw {
		out[i] = Identity{StakingID: []byte{byte(i)}, Weight: q[i], RawWeight: raw[i]}
	}
	return out
}

// The committed weights of a set are the quantization of its raw weights; each refusal below differs from the control in one thing.
func TestCheckQuantizedJudgesTheCommittedWeightsAgainstTheRawOnes(t *testing.T) {
	heavy := recordsOf(1_000_000, 1_000_000, 1_000_000, 1_000_000)
	require.Less(t, heavy[0].Weight, heavy[0].RawWeight, "the control is a quantized set")
	require.NoError(t, CheckQuantized(heavy))
	require.NoError(t, CheckQuantized(recordsOf(6, 1, 1, 1)), "below the cap q = x")

	for name, mutate := range map[string]func([]Identity){
		"a weight one above its quantization": func(ids []Identity) { ids[1].Weight++ },
		"a weight one below it":               func(ids []Identity) { ids[1].Weight-- },
		"the raw weight raised":               func(ids []Identity) { ids[2].RawWeight *= 2 },
		"the raw weight lowered":              func(ids []Identity) { ids[2].RawWeight /= 2 },
		"a zero raw weight":                   func(ids []Identity) { ids[0].RawWeight = 0 },
	} {
		ids := append([]Identity{}, heavy...)
		mutate(ids)
		require.ErrorIs(t, CheckQuantized(ids), ErrIdentity, name)
	}
	// q = x is the only valid record for a set within the cap
	small := recordsOf(6, 1, 1, 1)
	small[0].Weight = 5
	require.ErrorIs(t, CheckQuantized(small), ErrIdentity, "a set within the cap is never reduced")
	require.ErrorIs(t, CheckQuantized(nil), ErrIdentity, "no members")
}

func TestARecordCannotCommitMoreWeightThanItsRawWeight(t *testing.T) {
	i := Identity{StakingID: bytes.Repeat([]byte{0}, StakingIDLen), RootNodeID: "r", EVMNodeID: "e", RootKey: bytes.Repeat([]byte{2}, KeyLen), EVMKey: bytes.Repeat([]byte{3}, KeyLen),
		Weight: 5, RawWeight: 5, OperatorPayee: bytes.Repeat([]byte{1}, PayeeLen), ExposureDigest: bytes.Repeat([]byte{1}, DigestLen)}
	require.NoError(t, i.valid())
	i.RawWeight = 4
	require.ErrorIs(t, i.valid(), ErrIdentity, "q above x")
}
