package evmassign

import (
	"encoding/json"
	"os"
	"strconv"
	"testing"

	"github.com/stretchr/testify/require"
)

type quantVectors struct {
	B     uint64 `json:"b"`
	Cases []struct {
		Name  string   `json:"name"`
		B     uint64   `json:"b"`
		X     []string `json:"x"`
		Q     []string `json:"q"`
		S     string   `json:"s"`
		Error bool     `json:"error"`
	} `json:"cases"`
}

func u64s(t *testing.T, in []string) []uint64 {
	out := make([]uint64, len(in))
	for i, s := range in {
		v, err := strconv.ParseUint(s, 10, 64)
		require.NoError(t, err)
		out[i] = v
	}
	return out
}

// The vectors are generated by unicity-pos-contracts tools/quant_vectors.py with exact integer arithmetic; Quantize.sol and ureth's quant.rs
// are checked against the same file.
func TestQuantizeReproducesTheSharedVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/quant-vectors.json")
	require.NoError(t, err)
	var v quantVectors
	require.NoError(t, json.Unmarshal(raw, &v))
	require.EqualValues(t, 65536, v.B)
	require.Greater(t, len(v.Cases), 30)
	for _, c := range v.Cases {
		x := u64s(t, c.X)
		q, s, err := Quantize(x, c.B)
		if c.Error {
			require.ErrorIs(t, err, ErrQuantize, c.Name)
			continue
		}
		require.NoError(t, err, c.Name)
		require.Equal(t, u64s(t, c.Q), q, c.Name)
		require.Equal(t, u64s(t, []string{c.S})[0], s, c.Name)
	}
}

func TestQuantizeInvariants(t *testing.T) {
	const b = 65536
	for seed := uint64(1); seed <= 300; seed++ {
		n := 1 + int(seed*7919%100)
		x := make([]uint64, n)
		var total uint64
		mag := uint64(1) << (1 + seed%40)
		for i := range x {
			x[i] = (seed*2654435761+uint64(i)*40503)%mag + 1
			total += x[i]
		}
		q, _, err := Quantize(x, b)
		require.NoError(t, err)
		var sum uint64
		for i := range q {
			require.GreaterOrEqual(t, q[i], uint64(1))
			require.LessOrEqual(t, q[i], x[i])
			sum += q[i]
			for j := range q {
				if x[i] >= x[j] {
					require.GreaterOrEqual(t, q[i], q[j], "the raw order is preserved weakly")
				}
			}
			if total <= b {
				require.Equal(t, x[i], q[i])
			}
		}
		require.LessOrEqual(t, sum, uint64(b))
	}
}

// Each refusal differs from a valid input in one thing.
func TestQuantizeRefusals(t *testing.T) {
	_, _, err := Quantize([]uint64{1, 2, 3}, 100)
	require.NoError(t, err)
	for name, x := range map[string][]uint64{"empty": nil, "a zero": {1, 0, 3}, "overflow": {^uint64(0), 1}} {
		_, _, err := Quantize(x, 100)
		require.ErrorIs(t, err, ErrQuantize, name)
	}
	_, _, err = Quantize([]uint64{1, 1}, 2)
	require.ErrorIs(t, err, ErrQuantize, "n >= B")
}
