package evmstate

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/require"
)

func contains(slots []string, want word32, t testing.TB) bool {
	for _, s := range slots {
		if hexWord(t, s) == want {
			return true
		}
	}
	return false
}

func u(t testing.TB, s string) uint64 {
	v, err := strconv.ParseUint(s, 10, 64)
	require.NoError(t, err, s)
	return v
}

// Every slot formula must land on the slot the EVM itself read for the matching public getter (generated by the contracts' own test).
func TestCustodySlotsAreTheSlotsTheEVMReads(t *testing.T) {
	fx := loadFixture(t, "state-slots.json")
	checked := map[string]int{}
	for _, sc := range fx.Scenarios {
		for _, r := range sc.Reads {
			a := r.args(t)
			must := func(want word32, what string) {
				require.True(t, contains(r.Slots, want, t), "%s/%s: %s slot %x is not among the recorded %v", sc.Name, r.Name, what, want, r.Slots)
				checked[r.Name]++
			}
			switch r.Name {
			case "network":
				must(baseSlot(custodyNetwork), "network")
				require.Len(t, r.Slots, 1)
			case "roots":
				must(baseSlot(custodyRoots), "roots")
				require.Len(t, r.Slots, 1)
			case "limits":
				must(baseSlot(custodyLimits), "limits")
				require.Len(t, r.Slots, 1)
			case "recordCursor":
				must(baseSlot(custodyRecordCursor), "recordCursor")
				require.Len(t, r.Slots, 1)
			case "lastAckedAssignment":
				must(baseSlot(custodyLastAckedAssignment), "lastAckedAssignment")
				require.Len(t, r.Slots, 1)
			case "positions":
				must(slotWord(mapUint(baseSlot(custodyPositions), u(t, a[0])), positionsGenerationSlot), "positions[id] generation/retirementRequested")
			case "retirements":
				must(nested(custodyRetirements, u(t, a[0]), u(t, a[1])), "retirements[id][gen]")
				require.Len(t, r.Slots, 1)
			case "liveExposures":
				must(nested(custodyLiveExposures, u(t, a[0]), u(t, a[1])), "liveExposures[id][gen]")
				require.Len(t, r.Slots, 1)
			case "exposureChain":
				must(nested(custodyExposureChain, u(t, a[0]), u(t, a[1])), "exposureChain[id][gen]")
				require.Len(t, r.Slots, 1)
			case "maxLiabilityAnchor":
				must(nested(custodyMaxLiabilityAnchor, u(t, a[0]), u(t, a[1])), "maxLiabilityAnchor[id][gen]")
				require.Len(t, r.Slots, 1)
			case "generationLots":
				length := nested(custodyGenerationLots, u(t, a[0]), u(t, a[1]))
				must(length, "generationLots length")
				n := fieldUint(hexWord(t, r.Words[indexOf(t, r.Slots, length)]), 0, 8)
				require.Len(t, r.Slots, int(n)+1, "the length slot and one slot per element, no more")
				for i := uint64(0); i < n; i++ {
					must(arrayElement(length, i), "generationLots element")
				}
			case "lots":
				must(slotWord(mapUint(baseSlot(custodyLots), u(t, a[0])), lotRefCountSlot), "lots[id] refCount")
			case "session":
				base := mapSlot(baseSlot(custodySessions), unhexBytes(t, a[0]))
				for _, n := range []uint64{sessionStateSlot, sessionAssignmentSlot, sessionAttemptSlot, sessionIncumbentSlot} {
					must(slotWord(base, n), "session member")
				}
			case "assignments":
				must(slotWord(mapSlot(baseSlot(custodyAssignments), unhexBytes(t, a[0])), assignmentStateSlot), "assignments[id].state")
			default:
				t.Fatalf("unknown getter %q", r.Name)
			}
		}
	}
	for _, name := range []string{"network", "roots", "limits", "recordCursor", "lastAckedAssignment", "positions", "retirements", "liveExposures",
		"exposureChain", "maxLiabilityAnchor", "generationLots", "lots", "session", "assignments"} {
		require.Positive(t, checked[name], name)
	}
}

func unhexBytes(t testing.TB, s string) []byte { return unhex(t, s) }

func indexOf(t testing.TB, slots []string, want word32) int {
	for i, s := range slots {
		if hexWord(t, s) == want {
			return i
		}
	}
	t.Fatalf("slot %x not found", want)
	return -1
}

func TestRegistrySlotsAreTheSlotsTheEVMReadsAndWrites(t *testing.T) {
	fx := loadFixture(t, "registry-state-slots.json")
	for _, sc := range fx.Scenarios {
		for _, r := range sc.Reads {
			switch r.Name {
			case "recordCount":
				require.Equal(t, []string{"0x" + hexOf(registryKey("records.count"))}, r.Slots)
			case "recordTargetCount":
				require.Equal(t, []string{"0x" + hexOf(registryKey("records.targetCount"))}, r.Slots)
			case "retirement":
				require.Equal(t, []string{"0x" + hexOf(registryRetirementKey(sc.ID, sc.Generation))}, r.Slots, sc.Name)
			default:
				t.Fatalf("unknown read %q", r.Name)
			}
		}
	}
}

func hexOf(w word32) string {
	const digits = "0123456789abcdef"
	out := make([]byte, 64)
	for i, b := range w {
		out[2*i], out[2*i+1] = digits[b>>4], digits[b&15]
	}
	return string(out)
}
