// Package evmstate verifies Ethereum account and storage proofs of the P85 custody and registry contracts against the EVM state root the
// root already certified, and reads from them the facts a Retirement or RejectResult control needs
// (briefs/p85-pr1c-control-records.md sections 3 and 4).
package evmstate

import (
	"math/big"

	ethcrypto "github.com/ethereum/go-ethereum/crypto"
)

// The declared storage layout. Custody's slots are the solc layout of unicity-pos-contracts src/p85/StakeCustody.sol (variables in
// declaration order, one slot per word, struct members packed from the low-order byte); the registry's are fixed slots named
// keccak256("unicity.seal-registry/" + name). Every slot used here was checked against the slots the EVM itself reads for the matching
// public getter: testdata/state-slots.json and testdata/registry-state-slots.json are generated by the contracts' own tests.
const (
	custodyNetwork             = 4
	custodyRoots               = 8
	custodyLimits              = 11
	custodyLastAckedAssignment = 14
	custodyRecordCursor        = 15
	custodyPositions           = 22
	custodyGenerationLots      = 26
	custodyLots                = 27
	custodyRetirements         = 28
	custodyExposureChain       = 29
	custodyMaxLiabilityAnchor  = 30
	custodyLiveExposures       = 31
	custodyAssignments         = 32
	custodySessions            = 35
)

// ElectionPolicy's declared layout (forge inspect ElectionPolicy storageLayout): network, custody, and the publication mapping, whose
// struct members are one word each (primaryHash, kCommit, incumbent, incumbentExposureDigest, incumbentKeyDigest, policyDigest,
// contractsDigest, snapshotDigest, assignmentID, popSetDigest) followed by a packed word: published (1 byte), popCount (4), attempt (8).
const (
	electionNetwork      = 2
	electionCustody      = 3
	electionPublications = 16

	pubPrimaryHash, pubKCommit, pubIncumbent, pubIncumbentExposure, pubIncumbentKey = 0, 1, 2, 3, 4
	pubPolicy, pubContracts, pubSnapshot, pubAssignment, pubPopSet, pubFlags        = 5, 6, 7, 8, 9, 10
	pubPublishedOffset, pubPopCountOffset, pubAttemptOffset, pubLostOffset          = 0, 1, 5, 13
)

// member offsets inside their packed slot (bytes from the low-order end) and sizes
const (
	limitsLMaxOffset, limitsLMaxSize = 4, 4
	positionsGenerationSlot          = 4 // generation at offset 0 (8 bytes), retirementRequested at offset 24
	positionGenerationOffset         = 0
	positionRequestedOffset          = 24
	lotRefCountSlot                  = 2 // refCount at offset 3 (4 bytes)
	lotRefCountOffset, lotRefCountSz = 3, 4
	retirementImportedOffset         = 0
	sessionStateSlot                 = 0
	sessionAssignmentSlot            = 1
	sessionAttemptSlot               = 3
	sessionIncumbentSlot             = 4
	assignmentStateSlot              = 0
)

// custody session and assignment states
const (
	sessionOpen        = 1
	assignmentReserved = 1
)

func word(v uint64) []byte { return new(big.Int).SetUint64(v).FillBytes(make([]byte, 32)) }

func slotWord(slot [32]byte, add uint64) [32]byte {
	n := new(big.Int).SetBytes(slot[:])
	n.Add(n, new(big.Int).SetUint64(add))
	var out [32]byte
	n.FillBytes(out[:])
	return out
}

func keccak(parts ...[]byte) (out [32]byte) {
	var all []byte
	for _, p := range parts {
		all = append(all, p...)
	}
	copy(out[:], ethcrypto.Keccak256(all))
	return out
}

func baseSlot(n uint64) (out [32]byte) { copy(out[:], word(n)); return out }

// mapSlot is the slot of mapping[key] for a mapping declared at slot: keccak256(key . slot).
func mapSlot(slot [32]byte, key []byte) [32]byte { return keccak(key, slot[:]) }

func mapUint(slot [32]byte, key uint64) [32]byte { return mapSlot(slot, word(key)) }

// nested is mapping[id][generation].
func nested(base uint64, id, generation uint64) [32]byte {
	return mapUint(mapUint(baseSlot(base), id), generation)
}

// arrayElement is the slot of element i of a dynamic array declared at slot: keccak256(slot) + i.
func arrayElement(slot [32]byte, i uint64) [32]byte { return slotWord(keccak(slot[:]), i) }

func registryKey(name string) [32]byte { return keccak([]byte("unicity.seal-registry/" + name)) }

// registryRetirementKey is the registry's log key of the retirement of (id, generation): keccak256(abi.encode(RECORDS_RETIREMENT, id, generation)).
func registryRetirementKey(id, generation uint64) [32]byte {
	prefix := registryKey("records.retirement")
	return keccak(prefix[:], word(id), word(generation))
}

// field reads size bytes at byte offset (from the low-order end) of a packed storage word.
func field(w [32]byte, offset, size int) []byte { return w[32-offset-size : 32-offset] }

func fieldUint(w [32]byte, offset, size int) uint64 {
	return new(big.Int).SetBytes(field(w, offset, size)).Uint64()
}
