package evmstate

import (
	"encoding/json"
	"os"
	"testing"

	ethcrypto "github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/require"
	"github.com/unicitynetwork/bft-core/evmassign"
)

// testdata/publication.json is a copy of unicity-pos-contracts test/p85/fixtures/publication.json, generated by the contracts' own tests.
type pubFx struct {
	Deployment struct {
		NetworkWord string `json:"networkWord"`
		Custody     string `json:"custody"`
		Election    string `json:"election"`
	} `json:"deployment"`
	ResultID     string `json:"resultId"`
	AssignmentID string `json:"assignmentId"`
	Incumbent    string `json:"incumbentAssignmentId"`
	Attempt      uint64 `json:"attempt"`
	Snapshot     string `json:"snapshotDigest"`
	Expected     struct {
		PopSetDigest, PrimaryHash, KCommit, PolicyDigest, ContractsDigest string
		IncumbentExposureDigest, IncumbentKeyDigest                       string
	} `json:"expected"`
	Reserved  pubReads   `json:"reserved"`
	Published pubReads   `json:"published"`
	Lost      pubReads   `json:"lost"`
	Election  []pubReads `json:"electionReads"`
	Custody   []pubReads `json:"custodyReads"`
}

type pubReads struct {
	Name  string   `json:"name"`
	Slots []string `json:"slots"`
	Words []string `json:"words"`
}

func (r pubReads) into(t testing.TB, m map[word32]word32) {
	require.Len(t, r.Words, len(r.Slots))
	for i := range r.Slots {
		m[hexWord(t, r.Slots[i])] = hexWord(t, r.Words[i])
	}
}

func loadPubFx(t testing.TB) pubFx {
	raw, err := os.ReadFile("testdata/publication.json")
	require.NoError(t, err)
	var f pubFx
	require.NoError(t, json.Unmarshal(raw, &f))
	return f
}

type primaryWorld struct {
	fx       pubFx
	pins     Pins
	election map[word32]word32
	custody  map[word32]word32
}

func newPrimaryWorld(t testing.TB, scenario string) primaryWorld {
	fx := loadPubFx(t)
	pins := Pins{NetworkWord: hexWord(t, fx.Deployment.NetworkWord)}
	copy(pins.Custody[:], unhex(t, fx.Deployment.Custody))
	copy(pins.Election[:], unhex(t, fx.Deployment.Election))
	pins.CustodyCode = [32]byte(ethcrypto.Keccak256Hash([]byte("custody code")))
	pins.ElectionCode = [32]byte(ethcrypto.Keccak256Hash([]byte("election code")))
	w := primaryWorld{fx: fx, pins: pins, election: map[word32]word32{}, custody: map[word32]word32{}}
	switch scenario {
	case "reserved":
		fx.Reserved.into(t, w.election)
	case "lost":
		fx.Lost.into(t, w.election)
	default:
		fx.Published.into(t, w.election)
	}
	for _, r := range fx.Election {
		r.into(t, w.election)
	}
	for _, r := range fx.Custody {
		r.into(t, w.custody)
	}
	return w
}

func (p primaryWorld) witness(t testing.TB, resultID word32) (raw []byte, root word32) {
	world := buildWorld(t,
		contract{addr: p.pins.Election, codeHash: p.pins.ElectionCode, storage: p.election},
		contract{addr: p.pins.Custody, codeHash: p.pins.CustodyCode, storage: p.custody})
	reads := map[[20]byte]*recorder{p.pins.Election: newRecorder(p.election), p.pins.Custody: newRecorder(p.custody)}
	var f evmassign.PrimaryFacts
	// a pin mismatch ends the read early: the witness then holds what was read, and the verifier must refuse on the pin
	_ = readPrimary(reads[p.pins.Election], reads[p.pins.Custody], p.pins, resultID, &f)
	return witnessFor(t, world, reads), world.root
}

func TestPrimaryFactsAreProvenFromTheCertifiedState(t *testing.T) {
	w := newPrimaryWorld(t, "published")
	resultID := hexWord(t, w.fx.ResultID)
	raw, root := w.witness(t, resultID)
	f, err := Authority{Pins: w.pins}.VerifyPrimary(raw, root, resultID)
	require.NoError(t, err)

	require.True(t, f.Published)
	require.EqualValues(t, 4, f.PopCount)
	require.Equal(t, w.fx.Attempt, f.Attempt)
	require.Equal(t, resultID, f.ResultID)
	require.Equal(t, hexWord(t, w.fx.AssignmentID), f.AssignmentID)
	require.Equal(t, hexWord(t, w.fx.Incumbent), f.Incumbent)
	require.Equal(t, hexWord(t, w.fx.Snapshot), f.SnapshotDigest)
	require.Equal(t, hexWord(t, w.fx.Expected.PrimaryHash), f.PrimaryHash)
	require.Equal(t, hexWord(t, w.fx.Expected.KCommit), f.KCommit)
	require.Equal(t, hexWord(t, w.fx.Expected.PopSetDigest), f.PopSetDigest)
	require.Equal(t, hexWord(t, w.fx.Expected.PolicyDigest), f.PolicyDigest)
	require.Equal(t, hexWord(t, w.fx.Expected.ContractsDigest), f.ContractsDigest)
	require.Equal(t, hexWord(t, w.fx.Expected.IncumbentExposureDigest), f.IncumbentExposureDigest)
	require.Equal(t, hexWord(t, w.fx.Expected.IncumbentKeyDigest), f.IncumbentKeyDigest)
	require.True(t, f.Open)
	require.True(t, f.IncumbentIsLastAcked)
}

// The loss of a member's coverage after publication is its own proven word: the result stays published, and is marked lost.
func TestACoverageLossAfterPublicationIsAProvenWord(t *testing.T) {
	w := newPrimaryWorld(t, "lost")
	resultID := hexWord(t, w.fx.ResultID)
	raw, root := w.witness(t, resultID)
	f, err := Authority{Pins: w.pins}.VerifyPrimary(raw, root, resultID)
	require.NoError(t, err)
	require.True(t, f.Published)
	require.True(t, f.CoverageLost)
	require.EqualValues(t, 4, f.PopCount, "the other packed members are untouched")
	require.Equal(t, w.fx.Attempt, f.Attempt)

	healthy := newPrimaryWorld(t, "published")
	raw, root = healthy.witness(t, resultID)
	f, err = Authority{Pins: healthy.pins}.VerifyPrimary(raw, root, resultID)
	require.NoError(t, err)
	require.False(t, f.CoverageLost)
}

func TestAReservedResultIsNotPublished(t *testing.T) {
	w := newPrimaryWorld(t, "reserved")
	resultID := hexWord(t, w.fx.ResultID)
	raw, root := w.witness(t, resultID)
	f, err := Authority{Pins: w.pins}.VerifyPrimary(raw, root, resultID)
	require.NoError(t, err)
	require.False(t, f.Published)
	require.Zero(t, f.PopCount)
	require.Equal(t, hexWord(t, w.fx.Expected.KCommit), f.KCommit, "K is written with the reservation")
	require.True(t, f.Open)
}

// Each case changes one stored word or pin; the verdict (a refusal or a changed fact) must be that one's alone.
func TestPrimaryFactsFollowTheProvenWords(t *testing.T) {
	cases := []struct {
		name string
		mut  func(*primaryWorld, word32)
		want func(*testing.T, evmassign.PrimaryFacts)
	}{
		{"session closed", func(w *primaryWorld, res word32) {
			w.custody[slotWord(mapSlot(baseSlot(custodySessions), res[:]), sessionStateSlot)] = bigWord(3)
		}, func(t *testing.T, f evmassign.PrimaryFacts) {
			require.False(t, f.Open)
			require.True(t, f.IncumbentIsLastAcked)
		}},
		{"assignment no longer reserved", func(w *primaryWorld, res word32) {
			asg := hexWord(t, w.fx.AssignmentID)
			w.custody[slotWord(mapSlot(baseSlot(custodyAssignments), asg[:]), assignmentStateSlot)] = bigWord(2)
		}, func(t *testing.T, f evmassign.PrimaryFacts) { require.False(t, f.Open) }},
		{"another assignment acknowledged", func(w *primaryWorld, _ word32) {
			w.custody[baseSlot(custodyLastAckedAssignment)] = bigWord(77)
		}, func(t *testing.T, f evmassign.PrimaryFacts) {
			require.False(t, f.IncumbentIsLastAcked)
			require.True(t, f.Open)
		}},
		{"the session names another assignment", func(w *primaryWorld, res word32) {
			// another assignment that is itself open and reserved: only the link to the result's own assignment is wrong
			other := bigWord(5)
			w.custody[slotWord(mapSlot(baseSlot(custodySessions), res[:]), sessionAssignmentSlot)] = other
			w.custody[slotWord(mapSlot(baseSlot(custodyAssignments), other[:]), assignmentStateSlot)] = bigWord(1)
		}, func(t *testing.T, f evmassign.PrimaryFacts) { require.False(t, f.Open) }},
		{"the session extends another incumbent", func(w *primaryWorld, res word32) {
			w.custody[slotWord(mapSlot(baseSlot(custodySessions), res[:]), sessionIncumbentSlot)] = bigWord(9)
		}, func(t *testing.T, f evmassign.PrimaryFacts) {
			require.False(t, f.IncumbentIsLastAcked)
			require.True(t, f.Open)
		}},
		{"the attempt is read from the packed word", func(w *primaryWorld, res word32) {
			slot := slotWord(mapSlot(baseSlot(electionPublications), res[:]), pubFlags)
			flags := w.election[slot]
			flags[32-pubAttemptOffset-8+7] = 7 // attempt 7
			w.election[slot] = flags
		}, func(t *testing.T, f evmassign.PrimaryFacts) { require.EqualValues(t, 7, f.Attempt) }},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			w := newPrimaryWorld(t, "published")
			resultID := hexWord(t, w.fx.ResultID)
			tc.mut(&w, resultID)
			// a session-assignment change needs the matching assignment slot to exist for the reader; absent slots read as zero
			raw, root := w.witness(t, resultID)
			f, err := Authority{Pins: w.pins}.VerifyPrimary(raw, root, resultID)
			require.NoError(t, err)
			tc.want(t, f)
		})
	}
}

func TestPrimaryWitnessIsPinnedToTheDeployment(t *testing.T) {
	cases := []struct {
		name string
		mut  func(*primaryWorld)
		pin  func(*Pins)
		want error
	}{
		{"another election code", nil, func(p *Pins) { p.ElectionCode[0] ^= 1 }, ErrProof},
		{"another custody code", nil, func(p *Pins) { p.CustodyCode[0] ^= 1 }, ErrProof},
		{"another network", nil, func(p *Pins) { p.NetworkWord[0] ^= 1 }, ErrProof},
		{"election names another custody", func(w *primaryWorld) { w.election[baseSlot(electionCustody)] = bigWord(9) }, nil, ErrProof},
		{"election network differs", func(w *primaryWorld) { w.election[baseSlot(electionNetwork)] = bigWord(9) }, nil, ErrProof},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			w := newPrimaryWorld(t, "published")
			resultID := hexWord(t, w.fx.ResultID)
			good := w.pins
			if tc.mut != nil {
				tc.mut(&w)
			}
			raw, root := w.witness(t, resultID)
			pins := good
			if tc.pin != nil {
				tc.pin(&pins)
			} else {
				pins = w.pins
			}
			_, err := Authority{Pins: pins}.VerifyPrimary(raw, root, resultID)
			require.ErrorIs(t, err, tc.want)
		})
	}
}

func TestPrimaryWitnessShapeIsExact(t *testing.T) {
	w := newPrimaryWorld(t, "published")
	resultID := hexWord(t, w.fx.ResultID)
	raw, root := w.witness(t, resultID)

	d, err := decodeWitness(raw)
	require.NoError(t, err)
	one, err := Witness{Accounts: d.Accounts[:1]}.Encode()
	require.NoError(t, err)
	_, err = Authority{Pins: w.pins}.VerifyPrimary(one, root, resultID)
	require.ErrorIs(t, err, ErrWitness, "one account")

	// a slot proven but never read
	world := buildWorld(t,
		contract{addr: w.pins.Election, codeHash: w.pins.ElectionCode, storage: w.election},
		contract{addr: w.pins.Custody, codeHash: w.pins.CustodyCode, storage: w.custody})
	reads := map[[20]byte]*recorder{w.pins.Election: newRecorder(w.election), w.pins.Custody: newRecorder(w.custody)}
	var f evmassign.PrimaryFacts
	require.NoError(t, readPrimary(reads[w.pins.Election], reads[w.pins.Custody], w.pins, resultID, &f))
	reads[w.pins.Election].read[slotWord(mapSlot(baseSlot(electionPublications), resultID[:]), 11)] = true
	_, err = Authority{Pins: w.pins}.VerifyPrimary(witnessFor(t, world, reads), world.root, resultID)
	require.ErrorIs(t, err, ErrWitness, "an unused slot")

	// the wrong result: the slots of another result are not in the witness
	other := bigWord(0xabc)
	_, err = Authority{Pins: w.pins}.VerifyPrimary(raw, root, other)
	require.ErrorIs(t, err, ErrWitness)
}
