package bridgeprofile

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// The cache is imported from the pinned companion commit, never generated by
// this test. Replay consumes its fixture JSON and expectations independently
// of BuildCorpus; the subsequent comparison catches generator drift too.
func TestExternalSealedCorpus(t *testing.T) {
	root := "testdata/external-corpus"
	pinBytes, err := os.ReadFile(root + "/pin.json")
	require.NoError(t, err, "import the sealed companion snapshot before running the consumer")
	var pin struct{ Repository, Revision, Digest, Status string }
	require.NoError(t, json.Unmarshal(pinBytes, &pin))
	require.Equal(t, "ristik/native-bridge-plugins", pin.Repository)
	require.Len(t, pin.Revision, 40)
	require.Contains(t, []string{"sealed-candidate-unmerged", "merged-release"}, pin.Status)
	if os.Getenv("BRIDGEPROFILE_REQUIRE_MERGED_CORPUS") != "" {
		require.Equal(t, "merged-release", pin.Status, "release gate: companion snapshot must be merged")
	}
	root += "/vectors"
	manifest, err := os.ReadFile(root + "/SHA256SUMS")
	require.NoError(t, err)
	sum := sha256.Sum256(manifest)
	require.Equal(t, pin.Digest, hex.EncodeToString(sum[:]))
	marker, err := os.ReadFile(root + "/MANIFEST.sha256")
	require.NoError(t, err)
	require.Equal(t, pin.Digest, strings.TrimSpace(string(marker)))
	files := map[string][]byte{}
	for _, line := range strings.Split(strings.TrimSpace(string(manifest)), "\n") {
		hash, name, ok := strings.Cut(line, "  ")
		require.True(t, ok)
		require.False(t, filepath.IsAbs(name))
		require.NotContains(t, name, "..")
		require.NotContains(t, name, "\\")
		b, err := os.ReadFile(filepath.Join(root, name))
		require.NoError(t, err)
		sum := sha256.Sum256(b)
		require.Equal(t, hash, hex.EncodeToString(sum[:]), name)
		_, duplicate := files[name]
		require.False(t, duplicate)
		files[name] = b
	}
	var fs FixtureSet
	require.NoError(t, json.Unmarshal(files["config/fixtures.json"], &fs))
	seen := map[string]bool{}
	for _, family := range families {
		var cf CaseFile
		require.NoError(t, json.Unmarshal(files[family+"/cases.json"], &cf))
		require.Equal(t, family, cf.Family)
		for _, c := range cf.Cases {
			require.False(t, seen[c.ID])
			seen[c.ID] = true
			require.Equal(t, c.Expected, Replay(&fs, c), c.ID)
		}
	}
	generated, err := BuildCorpus()
	require.NoError(t, err)
	for name, b := range generated.Files {
		require.Equal(t, b, files[name], "external companion bytes differ: %s", name)
		delete(files, name)
	}
	require.Len(t, files, 2, "only VERSION and provenance may be added by sealing")
	require.Contains(t, files, "VERSION")
	require.Contains(t, files, "provenance.json")
	t.Logf("replayed %d external sealed cases at %s", len(seen), pin.Revision)
}
