// Package evmstatetest builds a real Merkle-Patricia EVM state from the published-result fixture (unicity-pos-contracts
// test/p85/fixtures/publication.json, generated by ElectionPolicy itself), so that tests of other packages can run the whole primary-proof
// route with the real authority: witness, state root, candidate and possession proofs.
package evmstatetest

import (
	"bytes"
	"context"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"strings"
	"testing"

	ethcommon "github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/core/types"
	ethcrypto "github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/trie"
	"github.com/ethereum/go-ethereum/triedb"
	"github.com/holiman/uint256"
	"github.com/stretchr/testify/require"

	"github.com/unicitynetwork/bft-core/evmassign"
	"github.com/unicitynetwork/bft-core/rootchain/evmstate"
)

type reads struct {
	Slots []string `json:"slots"`
	Words []string `json:"words"`
}

type identity struct {
	ID         uint64   `json:"id"`
	Generation uint64   `json:"generation"`
	Weight     uint64   `json:"weight"`
	RawWeight  uint64   `json:"rawWeight"`
	Payee      string   `json:"operatorPayee"`
	RootKey    string   `json:"rootKey"`
	EVMKey     string   `json:"evmKey"`
	LotIDs     []uint64 `json:"lotIds"`
}

type fixture struct {
	Deployment struct {
		NetworkWord string `json:"networkWord"`
		ChainID     uint64 `json:"chainId"`
		Custody     string `json:"custody"`
		Election    string `json:"election"`
	} `json:"deployment"`
	ResultID            string     `json:"resultId"`
	Identities          []identity `json:"identities"`
	IncumbentIdentities []identity `json:"incumbentIdentities"`
	Pops                []struct {
		ID        uint64 `json:"id"`
		EVMKey    string `json:"evmKey"`
		Signature string `json:"signature"`
	} `json:"pops"`
	Published     reads   `json:"published"`
	ElectionReads []reads `json:"electionReads"`
	CustodyReads  []reads `json:"custodyReads"`
}

// Published is the fixture's published result in a real state: the authority's pins, the state root, and a candidate with its possession
// proofs that the real verification route accepts.
type Published struct {
	Pins       evmstate.Pins
	Deployment evmassign.ElectionDeployment
	StateRoot  [32]byte
	ResultID   [32]byte
	Facts      evmassign.PrimaryFacts
	Candidate  evmassign.Candidate
	PoPs       []evmassign.EVMPoP
	Witness    []byte

	world *world
}

func unhex(t testing.TB, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
	require.NoError(t, err)
	return b
}

func word(t testing.TB, s string) (w [32]byte) {
	copy(w[32-len(unhex(t, s)):], unhex(t, s))
	return w
}

// Load reads the fixture at path and builds the state, the witness, the candidate and the proofs.
func Load(t testing.TB, path string) *Published {
	t.Helper()
	raw, err := os.ReadFile(path)
	require.NoError(t, err)
	var fx fixture
	require.NoError(t, json.Unmarshal(raw, &fx))

	p := &Published{ResultID: word(t, fx.ResultID)}
	p.Pins.NetworkWord = word(t, fx.Deployment.NetworkWord)
	copy(p.Pins.Custody[:], unhex(t, fx.Deployment.Custody))
	copy(p.Pins.Election[:], unhex(t, fx.Deployment.Election))
	p.Pins.CustodyCode = [32]byte(ethcrypto.Keccak256Hash([]byte("custody code")))
	p.Pins.ElectionCode = [32]byte(ethcrypto.Keccak256Hash([]byte("election code")))
	p.Deployment = evmassign.ElectionDeployment{Deployment: evmassign.Deployment{NetworkWord: p.Pins.NetworkWord, Custody: p.Pins.Custody}, Election: p.Pins.Election}
	new(big.Int).SetUint64(fx.Deployment.ChainID).FillBytes(p.Deployment.ChainID[:])
	p.Deployment.Election = p.Pins.Election

	election, custody := map[[32]byte][32]byte{}, map[[32]byte][32]byte{}
	into := func(m map[[32]byte][32]byte, r reads) {
		require.Len(t, r.Words, len(r.Slots))
		for i := range r.Slots {
			m[word(t, r.Slots[i])] = word(t, r.Words[i])
		}
	}
	into(election, fx.Published)
	for _, r := range fx.ElectionReads {
		into(election, r)
	}
	for _, r := range fx.CustodyReads {
		into(custody, r)
	}
	p.world = newWorld(t,
		contract{addr: p.Pins.Election, codeHash: p.Pins.ElectionCode, storage: election},
		contract{addr: p.Pins.Custody, codeHash: p.Pins.CustodyCode, storage: custody})
	p.StateRoot = p.world.root

	var err2 error
	p.Witness, err2 = evmstate.BuildPrimaryWitness(context.Background(), p.world, p.Pins, p.ResultID)
	require.NoError(t, err2)
	p.Facts, err2 = evmstate.Authority{Pins: p.Pins}.VerifyPrimary(p.Witness, p.StateRoot, p.ResultID)
	require.NoError(t, err2)

	nz := make([]byte, 32)
	nz[0] = 1
	ids := func(list []identity) []evmassign.Identity {
		out := make([]evmassign.Identity, len(list))
		for i, x := range list {
			var sid [32]byte
			new(big.Int).SetUint64(x.ID).FillBytes(sid[24:])
			ex := evmassign.LotsDigest(x.LotIDs)
			out[i] = evmassign.Identity{StakingID: sid[:], Generation: x.Generation, RootNodeID: "root-" + string(rune('a'+i)), RootKey: unhex(t, x.RootKey),
				EVMNodeID: "evm-" + string(rune('a'+i)), EVMKey: unhex(t, x.EVMKey), Weight: x.Weight, RawWeight: x.RawWeight, OperatorPayee: unhex(t, x.Payee), ExposureDigest: ex[:]}
		}
		return out
	}
	p.Candidate = evmassign.Candidate{Version: evmassign.CandidateVersion, Kind: evmassign.KindPrimary, Network: 1, Attempt: 9,
		Identities: ids(fx.Identities),
		Authorization: &evmassign.Authorization{Network: 1, Contracts: p.Facts.ContractsDigest[:], ResultID: p.ResultID[:], SnapshotDigest: p.Facts.SnapshotDigest[:],
			BaseRootBodyID: nz, BaseAssignmentHash: nz, K: ids(fx.IncumbentIdentities), ExposureDigest: nz, Policies: p.Facts.PolicyDigest[:]}}
	for _, x := range fx.Pops {
		p.PoPs = append(p.PoPs, evmassign.EVMPoP{ID: x.ID, EVMKey: unhex(t, x.EVMKey), Signature: unhex(t, x.Signature)})
	}
	require.NoError(t, evmassign.VerifyPrimary(p.Candidate, p.Deployment, p.Facts, p.PoPs), "the fixture's candidate and proofs verify against its own facts")
	return p
}

// ---- the world ---------------------------------------------------------------------------------------------------------------------------

type nodeList [][]byte

func (l *nodeList) Put(_, v []byte) error { *l = append(*l, bytes.Clone(v)); return nil }
func (l *nodeList) Delete([]byte) error   { return nil }

func newTrie() *trie.Trie { return trie.NewEmpty(triedb.NewDatabase(rawdb.NewMemoryDatabase(), nil)) }

type contract struct {
	addr     [20]byte
	codeHash [32]byte
	storage  map[[32]byte][32]byte
}

type world struct {
	t        testing.TB
	root     [32]byte
	state    *trie.Trie
	storage  map[ethcommon.Address]*trie.Trie
	contents map[ethcommon.Address]map[[32]byte][32]byte
}

func newWorld(t testing.TB, contracts ...contract) *world {
	w := &world{t: t, state: newTrie(), storage: map[ethcommon.Address]*trie.Trie{}, contents: map[ethcommon.Address]map[[32]byte][32]byte{}}
	for _, c := range contracts {
		st := newTrie()
		for slot, v := range c.storage {
			if v == ([32]byte{}) {
				continue
			}
			enc, err := rlp.EncodeToBytes(bytes.TrimLeft(v[:], "\x00"))
			require.NoError(t, err)
			require.NoError(t, st.Update(ethcrypto.Keccak256(slot[:]), enc))
		}
		w.storage[ethcommon.Address(c.addr)] = st
		w.contents[ethcommon.Address(c.addr)] = c.storage
		acct, err := rlp.EncodeToBytes(&types.StateAccount{Nonce: 1, Balance: uint256.NewInt(0), Root: st.Hash(), CodeHash: c.codeHash[:]})
		require.NoError(t, err)
		require.NoError(t, w.state.Update(ethcrypto.Keccak256(c.addr[:]), acct))
	}
	// unrelated accounts, so the state trie has real branches
	for i := 0; i < 24; i++ {
		var a [20]byte
		a[0], a[19] = 0xee, byte(i)
		acct, err := rlp.EncodeToBytes(&types.StateAccount{Nonce: uint64(i), Balance: uint256.NewInt(uint64(i)), Root: types.EmptyRootHash, CodeHash: types.EmptyCodeHash[:]})
		require.NoError(t, err)
		require.NoError(t, w.state.Update(ethcrypto.Keccak256(a[:]), acct))
	}
	w.root = w.state.Hash()
	return w
}

// Proof implements evmstate.ProofSource over the world.
func (w *world) Proof(_ context.Context, addr [20]byte, slots [][32]byte) ([][]byte, []evmstate.SlotProof, error) {
	var account nodeList
	if err := w.state.Prove(ethcrypto.Keccak256(addr[:]), &account); err != nil {
		return nil, nil, err
	}
	out := make([]evmstate.SlotProof, len(slots))
	for i, s := range slots {
		var nl nodeList
		if err := w.storage[ethcommon.Address(addr)].Prove(ethcrypto.Keccak256(s[:]), &nl); err != nil {
			return nil, nil, err
		}
		out[i] = evmstate.SlotProof{Value: w.contents[ethcommon.Address(addr)][s], Proofs: nl}
	}
	return account, out, nil
}

// WitnessFor builds the witness of another result id over the same world (it does not verify: the result is not published).
func (p *Published) WitnessFor(t testing.TB, result [32]byte) ([]byte, error) {
	t.Helper()
	return evmstate.BuildPrimaryWitness(context.Background(), p.world, p.Pins, result)
}
