package engineapi

import (
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/unicitynetwork/bft-core/shardnode"
)

// mustHex is a test helper for building fixed-length byte slices from a hex
// literal without inline error handling cluttering every case below.
func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	require.NoError(t, err)
	return b
}

// Golden vectors below were computed independently in Python
// (hashlib.sha256, not this package's own code) against the exact
// domain-separated construction documented on domainHash: prefix byte ‖
// sealHash ‖ round as big-endian uint64. Deriving them from an outside tool
// rather than "run the Go function once and paste its output" is the point
// — a golden vector generated by calling the code under test can't catch a
// bug in that code, only a later regression from it.
func TestDeriveAttributes_GoldenVectors(t *testing.T) {
	seal1 := mustHex(t, "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
	sealAB := make([]byte, 32)
	for i := range sealAB {
		sealAB[i] = 0xAB
	}

	cases := []struct {
		name           string
		p              shardnode.RoundParams
		parent         ParentHeader
		wantTimestamp  uint64
		wantPrevRandao string
		wantBeaconRoot string
	}{
		{
			name:           "seal1 round1, parent behind seal timestamp",
			p:              shardnode.RoundParams{Round: 1, SealHash: seal1, Timestamp: 1000},
			parent:         ParentHeader{Timestamp: 500},
			wantTimestamp:  1000, // seal wins: parent+1 (501) < seal (1000)
			wantPrevRandao: "400f784a704c9c757cbdc7066c3e8773c027b973f5de33a0c4d2ab99393cc411",
			wantBeaconRoot: "47865d9a0db2806f07218b62a10d70dfca0776df8b395270dc83ff91e08170cc",
		},
		{
			name:           "seal1 round2, parent at same timestamp as seal — must not collide",
			p:              shardnode.RoundParams{Round: 2, SealHash: seal1, Timestamp: 1000},
			parent:         ParentHeader{Timestamp: 1000},
			wantTimestamp:  1001, // parent+1 (1001) > seal (1000): parent wins, strictly increasing
			wantPrevRandao: "33dc683fb49b507a8c7fb1ada978306cca958ea2f7d8a710cc97bfd3ca339b28",
			wantBeaconRoot: "b12b85b1c46fdf783175ffda6aa3ee2d16e3a23709ef2d35d4c9a53ea830a656",
		},
		{
			name:           "sealAB round1000",
			p:              shardnode.RoundParams{Round: 1000, SealHash: sealAB, Timestamp: 1},
			parent:         ParentHeader{Timestamp: 0},
			wantTimestamp:  1,
			wantPrevRandao: "6cc83e17c442283d950805a76e66da8fe51332c44c30b82c1ae33c14b78aae13",
			wantBeaconRoot: "d262223112be1db154c4490687ca745cef5487e613b47ca69ec5aca1c92ffcbb",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := DeriveAttributes(c.p, c.parent)
			require.NoError(t, err)
			require.Equal(t, c.wantTimestamp, uint64(got.Timestamp))
			require.Equal(t, mustHex(t, c.wantPrevRandao), got.PrevRandao[:])
			require.Equal(t, mustHex(t, c.wantBeaconRoot), got.ParentBeaconBlockRoot[:])
			require.Equal(t, data20{}, got.SuggestedFeeRecipient, "zero address for the PoC")
			require.Empty(t, got.Withdrawals)
			require.NotNil(t, got.Withdrawals, "must be an empty slice, not nil — Engine API JSON wants [] not null")
		})
	}
}

func TestDeriveAttributes_RejectsEmptySealHash(t *testing.T) {
	_, err := DeriveAttributes(shardnode.RoundParams{Round: 1}, ParentHeader{})
	require.ErrorIs(t, err, ErrNoSealHash)
}

func TestDeriveAttributes_TwoIndependentCallsAgree(t *testing.T) {
	seal := mustHex(t, "aa"+"bb"+"cc"+"dd"+"ee"+"ff"+"00"+"11"+"22"+"33"+"44"+"55"+"66"+"77"+"88"+"99"+
		"aa"+"bb"+"cc"+"dd"+"ee"+"ff"+"00"+"11"+"22"+"33"+"44"+"55"+"66"+"77"+"88"+"99")
	p := shardnode.RoundParams{Round: 42, SealHash: seal, Timestamp: 123456}
	parent := ParentHeader{Timestamp: 123450}

	a, err := DeriveAttributes(p, parent)
	require.NoError(t, err)
	b, err := DeriveAttributes(p, parent)
	require.NoError(t, err)
	require.Equal(t, a, b, "same inputs must produce byte-identical attributes — this is the property multi-validator quorum depends on")
}

func TestVerify_AcceptsCorrectAttributes(t *testing.T) {
	p := shardnode.RoundParams{Round: 5, SealHash: []byte("0123456789012345678901234567890"), Timestamp: 100}
	parent := ParentHeader{Timestamp: 90}
	attrs, err := DeriveAttributes(p, parent)
	require.NoError(t, err)
	require.NoError(t, Verify(p, parent, attrs))
}

func TestVerify_RejectsTamperedTimestamp(t *testing.T) {
	p := shardnode.RoundParams{Round: 5, SealHash: []byte("0123456789012345678901234567890"), Timestamp: 100}
	parent := ParentHeader{Timestamp: 90}
	attrs, err := DeriveAttributes(p, parent)
	require.NoError(t, err)

	attrs.Timestamp = attrs.Timestamp + 1000 // a leader claiming a different clock
	err = Verify(p, parent, attrs)
	require.Error(t, err)
	require.Contains(t, err.Error(), "timestamp")
}

func TestVerify_RejectsTamperedFeeRecipient(t *testing.T) {
	p := shardnode.RoundParams{Round: 5, SealHash: []byte("0123456789012345678901234567890"), Timestamp: 100}
	parent := ParentHeader{Timestamp: 90}
	attrs, err := DeriveAttributes(p, parent)
	require.NoError(t, err)

	attrs.SuggestedFeeRecipient = data20{0x01} // a leader trying to redirect fees
	err = Verify(p, parent, attrs)
	require.Error(t, err)
	require.Contains(t, err.Error(), "suggestedFeeRecipient")
}

func TestVerify_RejectsNonEmptyWithdrawals(t *testing.T) {
	p := shardnode.RoundParams{Round: 5, SealHash: []byte("0123456789012345678901234567890"), Timestamp: 100}
	parent := ParentHeader{Timestamp: 90}
	attrs, err := DeriveAttributes(p, parent)
	require.NoError(t, err)

	attrs.Withdrawals = []WithdrawalV1{{Index: 1}}
	err = Verify(p, parent, attrs)
	require.Error(t, err)
	require.Contains(t, err.Error(), "withdrawals")
}
