package engineapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
)

/*
The pinned execution profile, and the standard read that verifies it (issue #89 item 2).

A matching genesis hash binds the genesis BLOCK. It does not bind a fork scheduled by timestamp
later in the chain's life: a spec that schedules Prague for some future time has exactly the same
genesis block as one that schedules nothing, because a fork that has not activated changes no
genesis header field. Measured on the pinned client (189c0df3), two reth instances started from the
generated spec with and without `pragueTime` report the same chain id and the same block-0 hash.

An earlier revision of docs/design/f1-baseline.md §5.8 recorded this as closable only by "a
fork-schedule read the Engine API does not offer". The Engine API does not offer one, but the
standard eth_* namespace does: EIP-7910's eth_config reports the loaded spec's current fork and the
next and last scheduled ones, and the pinned client implements it (EthConfigApi,
crates/rpc/rpc-eth-api/src/helpers/config.rs). No new Engine method and no client divergence.

What the profile pins is what this adapter can actually drive: the V3 Engine API, i.e. Cancun, from
genesis, with nothing scheduled after it. Concretely, eth_config's `current` must be the fork
activated at timestamp 0 with exactly Cancun's system contract, Cancun's blob schedule and Cancun's
precompile set, and `next` and `last` must both be null. Anything else is refused, including a spec
that is behind the profile (Shanghai only) as well as one ahead of it.

Which connection it reads, and what that does and does not establish. eth_config is NOT in the
eth_* subset the Engine API specification requires on the authenticated port; the pinned client
answers "Method not found" there (measured). So it is read over the plain connection, and it binds
the ENGINE connection's schedule only through the pairing checks: chain id and genesis are required
to agree across the two connections before this runs. That is the same-process assumption recorded
in docs/design/f1-baseline.md §5.8 — two clients sharing a genesis agree on both values — and this
check does not remove it. What it removes is the case where the one client both URLs address has
loaded a spec that will later require engine_newPayloadV4+.
*/

// pinnedProfile is eth_config's `current` for the profile, as the pinned client reports it for a spec
// generated by `ubft engine-api genesis` (engineapi/testdata/eth_config_cancun_at_genesis.json).
// forkId is deliberately absent: it is a checksum over the genesis hash and the activated forks, so
// it differs per deployment genesis and is bound by the genesis checks, not by the profile.
var pinnedProfile = struct {
	activationTime  uint64
	blobSchedule    blobScheduleJSON
	systemContracts map[string]string
	precompiles     map[string]string
}{
	activationTime: 0,
	blobSchedule:   blobScheduleJSON{Target: 3, Max: 6, BaseFeeUpdateFraction: 3338477},
	systemContracts: map[string]string{
		"BEACON_ROOTS_ADDRESS": "0x000f3df6d732807ef1319fb7b8bb8522d0beac02",
	},
	precompiles: map[string]string{
		"ECREC":                "0x0000000000000000000000000000000000000001",
		"SHA256":               "0x0000000000000000000000000000000000000002",
		"RIPEMD160":            "0x0000000000000000000000000000000000000003",
		"ID":                   "0x0000000000000000000000000000000000000004",
		"MODEXP":               "0x0000000000000000000000000000000000000005",
		"BN254_ADD":            "0x0000000000000000000000000000000000000006",
		"BN254_MUL":            "0x0000000000000000000000000000000000000007",
		"BN254_PAIRING":        "0x0000000000000000000000000000000000000008",
		"BLAKE2F":              "0x0000000000000000000000000000000000000009",
		"KZG_POINT_EVALUATION": "0x000000000000000000000000000000000000000a",
	},
}

// PinnedProfileName is how diagnostics and doctor name the profile.
const PinnedProfileName = "Cancun at genesis, nothing scheduled after"

type blobScheduleJSON struct {
	Target                uint64 `json:"target"`
	Max                   uint64 `json:"max"`
	BaseFeeUpdateFraction uint64 `json:"baseFeeUpdateFraction"`
}

// forkConfigJSON is one of eth_config's current/next/last entries (EIP-7910). Pointers distinguish
// a field that is absent from one that is zero: an absent activation time must not read as "at
// genesis", for the same reason decodeBlockHeader refuses a missing hash.
type forkConfigJSON struct {
	ActivationTime  *uint64           `json:"activationTime"`
	BlobSchedule    *blobScheduleJSON `json:"blobSchedule"`
	ChainID         *quantity         `json:"chainId"`
	ForkID          string            `json:"forkId"`
	Precompiles     map[string]string `json:"precompiles"`
	SystemContracts map[string]string `json:"systemContracts"`
}

// ExecutionProfile is what CheckExecutionProfile validated, returned so a caller that reports it
// (doctor) uses the value the check saw rather than issuing another request — the #89 item 4 rule.
type ExecutionProfile struct {
	ForkID string
}

// Config calls eth_config on the plain endpoint and returns the raw result.
func (c *EthClient) Config(ctx context.Context) (json.RawMessage, error) {
	var raw json.RawMessage
	if err := c.call(ctx, "eth_config", nil, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

// CheckExecutionProfile refuses an execution client whose loaded chain spec is not the pinned
// profile. wantChainID is the shard conf's chain_id; eth_config reports the chain id per fork, and it
// is compared too so that a response for another chain can never pass as a matching profile.
// See the comment at the top of this file for what the check does and does not establish.
func (a *Adapter) CheckExecutionProfile(ctx context.Context, wantChainID uint64) (ExecutionProfile, error) {
	raw, err := a.eth.Config(ctx)
	if err != nil {
		return ExecutionProfile{}, fmt.Errorf("engineapi: reading eth_config (EIP-7910) over the plain connection: %w", err)
	}
	return checkProfile(raw, wantChainID)
}

func checkProfile(raw json.RawMessage, wantChainID uint64) (ExecutionProfile, error) {
	if isJSONNull(raw) {
		return ExecutionProfile{}, errors.New("engineapi: eth_config returned no fork configuration")
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return ExecutionProfile{}, fmt.Errorf("engineapi: decoding eth_config: %w", err)
	}

	// next and last must be PRESENT and null. EIP-7910 reports "nothing scheduled" as null; a response
	// that omits the keys has not said that, and treating absence as "nothing scheduled" would let an
	// incomplete answer pass as the one this check exists to demand.
	for _, key := range []string{"next", "last"} {
		v, ok := top[key]
		if !ok {
			return ExecutionProfile{}, fmt.Errorf("engineapi: eth_config has no %q entry, so it does not say whether a fork is scheduled", key)
		}
		if !isJSONNull(v) {
			var f forkConfigJSON
			when := "an unreadable time"
			if json.Unmarshal(v, &f) == nil && f.ActivationTime != nil {
				when = fmt.Sprintf("timestamp %d", *f.ActivationTime)
			}
			return ExecutionProfile{}, fmt.Errorf("engineapi: execution client's chain spec schedules a fork at %s after its current one "+
				"(eth_config %q is not null); the pinned profile is %s, because this adapter speaks only the V3 Engine API",
				when, key, PinnedProfileName)
		}
	}

	curRaw, ok := top["current"]
	if !ok || isJSONNull(curRaw) {
		return ExecutionProfile{}, errors.New("engineapi: eth_config has no current fork configuration")
	}
	var cur forkConfigJSON
	if err := json.Unmarshal(curRaw, &cur); err != nil {
		return ExecutionProfile{}, fmt.Errorf("engineapi: decoding eth_config current fork: %w", err)
	}

	if cur.ChainID == nil {
		return ExecutionProfile{}, errors.New("engineapi: eth_config current fork reports no chain id")
	}
	if uint64(*cur.ChainID) != wantChainID {
		return ExecutionProfile{}, fmt.Errorf("engineapi: eth_config reports chainId=%d, shard conf says %d", uint64(*cur.ChainID), wantChainID)
	}
	if cur.ActivationTime == nil {
		return ExecutionProfile{}, errors.New("engineapi: eth_config current fork reports no activation time")
	}
	if *cur.ActivationTime != pinnedProfile.activationTime {
		return ExecutionProfile{}, fmt.Errorf("engineapi: execution client's current fork activated at timestamp %d; the pinned profile is %s",
			*cur.ActivationTime, PinnedProfileName)
	}
	if cur.BlobSchedule == nil {
		return ExecutionProfile{}, errors.New("engineapi: eth_config current fork reports no blob schedule")
	}
	if *cur.BlobSchedule != pinnedProfile.blobSchedule {
		return ExecutionProfile{}, fmt.Errorf("engineapi: execution client's blob schedule is %+v; the pinned profile (Cancun) has %+v",
			*cur.BlobSchedule, pinnedProfile.blobSchedule)
	}
	if d := diffAddressSet(cur.SystemContracts, pinnedProfile.systemContracts); d != "" {
		return ExecutionProfile{}, fmt.Errorf("engineapi: execution client's system contracts differ from the pinned profile (%s): %s",
			PinnedProfileName, d)
	}
	if d := diffAddressSet(cur.Precompiles, pinnedProfile.precompiles); d != "" {
		return ExecutionProfile{}, fmt.Errorf("engineapi: execution client's precompiles differ from the pinned profile (%s): %s",
			PinnedProfileName, d)
	}
	return ExecutionProfile{ForkID: cur.ForkID}, nil
}

// diffAddressSet compares two name→address maps, addresses case-insensitively, and describes the
// difference; "" means equal. A nil map (the field absent) is compared as empty, which then differs
// from the non-empty pinned set and is refused.
func diffAddressSet(got, want map[string]string) string {
	var extra, missing, changed []string
	for name, addr := range got {
		w, ok := want[name]
		switch {
		case !ok:
			extra = append(extra, name)
		case !strings.EqualFold(addr, w):
			changed = append(changed, fmt.Sprintf("%s at %s, want %s", name, addr, w))
		}
	}
	for name := range want {
		if _, ok := got[name]; !ok {
			missing = append(missing, name)
		}
	}
	if len(extra)+len(missing)+len(changed) == 0 {
		return ""
	}
	sort.Strings(extra)
	sort.Strings(missing)
	sort.Strings(changed)
	var b bytes.Buffer
	for _, part := range []struct {
		label string
		names []string
	}{{"unexpected", extra}, {"missing", missing}, {"moved", changed}} {
		if len(part.names) > 0 {
			if b.Len() > 0 {
				b.WriteString("; ")
			}
			fmt.Fprintf(&b, "%s %s", part.label, strings.Join(part.names, ", "))
		}
	}
	return b.String()
}
