package certifiedstore

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"math/big"
	"path/filepath"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/rawdb"
	ethtypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/trie"
	"github.com/ethereum/go-ethereum/triedb"
	"github.com/holiman/uint256"
	"github.com/stretchr/testify/require"
	testcertificates "github.com/unicitynetwork/bft-core/internal/testutils/certificates"
	testtrustbase "github.com/unicitynetwork/bft-core/internal/testutils/trustbase"
	"github.com/unicitynetwork/bft-core/network/protocol/certification"
	"github.com/unicitynetwork/bft-core/registrygenesis"
	"github.com/unicitynetwork/bft-core/registryproof"
	abcrypto "github.com/unicitynetwork/bft-go-base/crypto"
	"github.com/unicitynetwork/bft-go-base/types"
	bolt "go.etcd.io/bbolt"
)

/*
Fixtures: a deployment generated by registrygenesis (the #153 §5.4 configuration and the merged registry
artifact), a chain of certified EVM blocks whose registry storage is finalized for their rounds, and really
signed unicity certificates over the full shard configuration, verified against a trust base the tests
configure. The signing key is fixed, so a child process builds certificates the parent's trust base accepts.
*/

var fixtureKey = bytes.Repeat([]byte{0x42}, 32)

type block struct {
	Hash      common.Hash
	Number    uint64
	StateRoot common.Hash
	Round     uint64
	Evidence  registryproof.Evidence
}

type trustStore struct{ tb *types.RootTrustBaseV1 }

func (s trustStore) GetByEpoch(_ context.Context, epoch uint64) (*types.RootTrustBaseV1, error) {
	if epoch != s.tb.GetEpoch() {
		return nil, fmt.Errorf("no trust base for root epoch %d", epoch)
	}
	return s.tb, nil
}

// multiTrust serves several root epochs, as a trust base store that has seen an epoch change would.
type multiTrust []*types.RootTrustBaseV1

func (m multiTrust) GetByEpoch(_ context.Context, epoch uint64) (*types.RootTrustBaseV1, error) {
	for _, tb := range m {
		if tb.GetEpoch() == epoch {
			return tb, nil
		}
	}
	return nil, fmt.Errorf("no trust base for root epoch %d", epoch)
}

// reseal re-signs uc's seal at root epoch epoch with signer, under the node id that signed it.
func (f *fixture) reseal(uc *types.UnicityCertificate, epoch uint64, signer abcrypto.Signer) *types.UnicityCertificate {
	var id string
	for k := range uc.UnicitySeal.Signatures {
		id = k
	}
	uc.UnicitySeal.Epoch, uc.UnicitySeal.Signatures = epoch, nil
	require.NoError(f.t, uc.UnicitySeal.Sign(id, signer))
	return uc
}

type fixture struct {
	t        *testing.T
	signer   abcrypto.Signer
	trust    trustStore
	genesis  *registrygenesis.Genesis
	full     *types.PartitionDescriptionRecord
	codeHash common.Hash
	blocks   []block
	ctx      Context
}

func vectorConfig(network types.NetworkID) *types.PartitionDescriptionRecord {
	return &types.PartitionDescriptionRecord{
		Version: 1, NetworkID: network, PartitionID: 8, T2Timeout: 5 * time.Second,
		PartitionParams: map[string]string{registrygenesis.ChainIDParam: "1337"}, Epoch: 0,
		Validators: []*types.NodeInfo{{NodeID: "validator-1", SigKey: append([]byte{0x02}, make([]byte, 32)...), Stake: 1}},
	}
}

func newFixture(t *testing.T, blocks int) *fixture { return newFixtureFor(t, 3, blocks) }

func newFixtureFor(t *testing.T, network types.NetworkID, blocks int) *fixture {
	signer, err := abcrypto.NewInMemorySecp256K1SignerFromKey(fixtureKey)
	require.NoError(t, err)
	tb, ok := testtrustbase.NewTrustBase(t, signer).(*types.RootTrustBaseV1)
	require.True(t, ok)

	art, err := registrygenesis.PinnedArtifact()
	require.NoError(t, err)
	pins := registrygenesis.Pins{RootEpoch: 1, RegistryCodeHash: art.CodeHash, SystemAddress: registrygenesis.SystemAddress, RegistryAddress: registryproof.RegistryAddress}
	g, err := registrygenesis.Generate(vectorConfig(network), pins, art, registrygenesis.DefaultEVMParams)
	require.NoError(t, err)
	full, err := g.FullConfig()
	require.NoError(t, err)

	f := &fixture{t: t, signer: signer, trust: trustStore{tb: tb}, genesis: g, full: full, codeHash: art.CodeHash}
	f.ctx = Context{
		NetworkID: full.NetworkID, PartitionID: full.PartitionID, ShardID: types.ShardID{},
		FullShardConfHash: g.FullShardConfHash().Bytes(), Registry: g.ProofContext(), TrustBases: f.trust,
	}
	f.blocks = []block{{Hash: g.EVMGenesisHash(), Number: 0, StateRoot: g.StateRoot(), Round: 0, Evidence: g.Evidence()}}
	for i := 1; i <= blocks; i++ {
		f.blocks = append(f.blocks, f.executed(f.blocks[i-1], uint64(i), uint64(4+i)))
	}
	return f
}

type nodeList [][]byte

func (l *nodeList) Put(_, v []byte) error { *l = append(*l, bytes.Clone(v)); return nil }
func (l *nodeList) Delete([]byte) error   { return nil }

func newTrie() *trie.Trie { return trie.NewEmpty(triedb.NewDatabase(rawdb.NewMemoryDatabase(), nil)) }

func word(v uint64) common.Hash { return common.BigToHash(new(big.Int).SetUint64(v)) }

// executed builds the block executing partition round `round` on parent, with registry storage as a
// successful open and finalize leave it (#153 §6.2, §6.3).
func (f *fixture) executed(parent block, round, rootRound uint64) block {
	t := f.t
	words := f.genesis.Storage()
	named := func(s string) common.Hash { return crypto.Keccak256Hash([]byte(s)) }
	for k, v := range map[string]common.Hash{
		"clock.rootRound": word(rootRound), "origin.rootEpoch": word(1), "origin.timestamp": word(1_700_000_000 + rootRound),
		"origin.treeRoot": named(fmt.Sprint("U", rootRound)), "origin.identity": named(fmt.Sprint("O", rootRound)),
		"origin.trHash": named(fmt.Sprint("T", rootRound)), "round.authorized": word(round),
		"input.commitment": named(fmt.Sprint("X", round)), "certified.round": word(parent.Round),
		"certified.stateHash": parent.StateRoot, "outcomes.round": word(round), "outcomes.commitment": named(fmt.Sprint("R", round)),
	} {
		words[k] = v
	}
	storage := newTrie()
	paths := make([][]byte, registryproof.FieldCount)
	for i, name := range registryproof.SlotNames {
		key := registryproof.SlotKey(i)
		paths[i] = crypto.Keccak256(key[:])
		if w := words[name]; w != (common.Hash{}) {
			v, err := rlp.EncodeToBytes(common.TrimLeftZeroes(w[:]))
			require.NoError(t, err)
			require.NoError(t, storage.Update(paths[i], v))
		}
	}
	account, err := rlp.EncodeToBytes(&ethtypes.StateAccount{Balance: new(uint256.Int), Root: storage.Hash(), CodeHash: f.codeHash.Bytes()})
	require.NoError(t, err)
	state := newTrie()
	accountPath := crypto.Keccak256(registryproof.RegistryAddress[:])
	require.NoError(t, state.Update(accountPath, account))

	withdrawals, beacon, zero := ethtypes.EmptyWithdrawalsHash, common.Hash{}, uint64(0)
	h := &ethtypes.Header{
		ParentHash: parent.Hash, UncleHash: ethtypes.EmptyUncleHash, Root: state.Hash(), TxHash: ethtypes.EmptyTxsHash,
		ReceiptHash: ethtypes.EmptyReceiptsHash, Difficulty: new(big.Int), Number: new(big.Int).SetUint64(parent.Number + 1),
		GasLimit: 30_000_000, Time: 1_700_000_000 + parent.Number + 1, Extra: named(fmt.Sprint("X", round)).Bytes(),
		BaseFee: big.NewInt(7), WithdrawalsHash: &withdrawals, BlobGasUsed: &zero, ExcessBlobGas: &zero, ParentBeaconRoot: &beacon,
	}
	header, err := rlp.EncodeToBytes(h)
	require.NoError(t, err)
	var accountProof nodeList
	require.NoError(t, state.Prove(accountPath, &accountProof))
	ev := registryproof.Evidence{Header: header, AccountProof: accountProof, StorageProofs: make([][][]byte, registryproof.FieldCount)}
	for i := range paths {
		var p nodeList
		require.NoError(t, storage.Prove(paths[i], &p))
		ev.StorageProofs[i] = p
	}
	return block{Hash: h.Hash(), Number: parent.Number + 1, StateRoot: h.Root, Round: round, Evidence: ev}
}

// genesisHeaderVariant re-encodes the genesis header with another timestamp: a block-0 header at the genesis
// state root whose hash is not the configured EVM genesis hash, so the genesis witness proves it.
func (f *fixture) genesisHeaderVariant() (common.Hash, []byte) {
	var h ethtypes.Header
	require.NoError(f.t, rlp.DecodeBytes(f.blocks[0].Evidence.Header, &h))
	h.Time++
	enc, err := rlp.EncodeToBytes(&h)
	require.NoError(f.t, err)
	require.NotEqual(f.t, f.blocks[0].Hash, h.Hash())
	return h.Hash(), enc
}

// inputRecord is the certified input record for block i: genesis history for block 0 (no block, state and
// previous state at the genesis state, #153 §7.3 E2), and a block-naming record for later blocks.
func (f *fixture) inputRecord(i int) *types.InputRecord {
	b := f.blocks[i]
	ir := &types.InputRecord{
		Version: 1, RoundNumber: b.Round, Epoch: 0, Hash: b.StateRoot.Bytes(), SummaryValue: []byte{}, Timestamp: 1_700_000_000 + b.Round,
	}
	if i == 0 {
		ir.PreviousHash = b.StateRoot.Bytes()
	} else {
		ir.PreviousHash = f.blocks[i-1].StateRoot.Bytes()
		ir.BlockHash = b.Hash.Bytes()
	}
	return ir
}

func technicalFor(round uint64) *certification.TechnicalRecord {
	return &certification.TechnicalRecord{Round: round + 1, Epoch: 0, Leader: "leader", StatHash: bytes.Repeat([]byte{0xa1}, 32), FeeHash: bytes.Repeat([]byte{0xa2}, 32)}
}

// certify signs a certificate for ir and tr over the full shard configuration.
func (f *fixture) certify(signer abcrypto.Signer, ir *types.InputRecord, tr *certification.TechnicalRecord, rootRound uint64) *types.UnicityCertificate {
	trHash, err := tr.Hash()
	require.NoError(f.t, err)
	uc := testcertificates.CreateUnicityCertificate(f.t, signer, ir, f.full, rootRound, bytes.Repeat([]byte{0xb0}, 32), trHash)
	require.NotNil(f.t, uc)
	return uc
}

// record builds the verified record for block i.
func (f *fixture) record(i int) Record { return f.recordWith(i, nil) }

// recordWith builds the record for block i after change edits the input record, technical record or record.
func (f *fixture) recordWith(i int, change func(ir *types.InputRecord, tr *certification.TechnicalRecord, r *Record)) Record {
	b := f.blocks[i]
	ir := f.inputRecord(i)
	tr := technicalFor(b.Round)
	r := Record{BlockHash: b.Hash, BlockNumber: b.Number, StateRoot: b.StateRoot, PartitionRound: b.Round, Technical: tr, Witness: b.Evidence}
	if change != nil {
		change(ir, tr, &r)
	}
	if r.Certificate == nil {
		r.Certificate = f.certify(f.signer, ir, tr, 4+b.Round)
	}
	return r
}

func (f *fixture) open(path string, retain int) *Store {
	s, err := Open(path, Settings{Retain: retain})
	require.NoError(f.t, err)
	f.t.Cleanup(func() { _ = s.Close() })
	return s
}

func tempDB(t *testing.T) string { return filepath.Join(t.TempDir(), "certified.db") }

// publishChain publishes blocks 0..n in order.
func (f *fixture) publishChain(s *Store, n int) {
	for i := 0; i <= n; i++ {
		require.NoError(f.t, s.Publish(context.Background(), f.ctx, f.record(i)), "block %d", i)
	}
}

// contents copies every key and value in the store's bucket.
func contents(t *testing.T, s *Store) map[string][]byte {
	out := map[string][]byte{}
	err := s.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket(bucketName)
		if b == nil {
			return nil
		}
		return b.ForEach(func(k, v []byte) error {
			out[string(k)] = bytes.Clone(v)
			return nil
		})
	})
	require.NoError(t, err)
	return out
}

func putRaw(t *testing.T, s *Store, key string, value []byte) {
	require.NoError(t, s.db.Update(func(tx *bolt.Tx) error { return tx.Bucket(bucketName).Put([]byte(key), value) }))
}

func deleteRaw(t *testing.T, s *Store, key string) {
	require.NoError(t, s.db.Update(func(tx *bolt.Tx) error { return tx.Bucket(bucketName).Delete([]byte(key)) }))
}

// reencode rewrites a stored record through change and re-encodes it with a valid digest.
func reencode(t *testing.T, raw []byte, change func(sr *storedRecord)) []byte {
	sr, err := decodeRecord(raw)
	require.NoError(t, err)
	change(&sr)
	payload, err := types.Cbor.Marshal(sr)
	require.NoError(t, err)
	return envelopeWith(t, sr.Version, payload)
}

func envelopeWith(t *testing.T, version uint32, payload []byte) []byte {
	sum := sha256Sum(payload)
	out, err := types.Cbor.Marshal(envelope{Version: version, Payload: payload, Digest: sum})
	require.NoError(t, err)
	return out
}

var errInjected = errors.New("injected failure")
