package f6arecord

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"sync"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/trie"
	"github.com/ethereum/go-ethereum/triedb"
	"github.com/holiman/uint256"
	"github.com/stretchr/testify/require"
	"github.com/unicitynetwork/bft-core/registrygenesis"
	"github.com/unicitynetwork/bft-core/registryproof"
	"github.com/unicitynetwork/bft-core/registrywitness"
	bfttypes "github.com/unicitynetwork/bft-go-base/types"
)

/*
Fixtures: a deployment generated by registrygenesis from the #153 §5.4 configuration and the merged registry
artifact, and a chain of certified EVM blocks on it. Each block after genesis carries registry storage as a
successful open and finalize would leave it (#153 §6.2, §6.3), committed to a real state trie with the pinned
code hash, so registryproof.Verify accepts its evidence as a finalized parent. The chain is built with
go-ethereum's trie package; it is fixture data, not an execution of the registry.
*/

type deployment struct {
	genesis  *registrygenesis.Genesis
	ctx      registryproof.Context
	codeHash common.Hash
}

func vectorConfig(network bfttypes.NetworkID) *bfttypes.PartitionDescriptionRecord {
	return &bfttypes.PartitionDescriptionRecord{
		Version: 1, NetworkID: network, PartitionID: 8, T2Timeout: 5 * time.Second,
		PartitionParams: map[string]string{registrygenesis.ChainIDParam: "1337"}, Epoch: 0,
		Validators: []*bfttypes.NodeInfo{{NodeID: "validator-1", SigKey: append([]byte{0x02}, make([]byte, 32)...), Stake: 1}},
	}
}

func newDeployment(t testing.TB, network bfttypes.NetworkID) *deployment {
	art, err := registrygenesis.PinnedArtifact()
	require.NoError(t, err)
	pins := registrygenesis.Pins{RootEpoch: 1, RegistryCodeHash: art.CodeHash, SystemAddress: registrygenesis.SystemAddress, RegistryAddress: registryproof.RegistryAddress}
	g, err := registrygenesis.Generate(vectorConfig(network), pins, art, registrygenesis.DefaultEVMParams)
	require.NoError(t, err)
	return &deployment{genesis: g, ctx: g.ProofContext(), codeHash: art.CodeHash}
}

// block is one certified EVM block with the evidence a node would capture for it.
type block struct {
	Hash           common.Hash
	Parent         common.Hash
	Number         uint64
	StateRoot      common.Hash
	PartitionRound uint64
	Evidence       registryproof.Evidence
}

func (d *deployment) genesisBlock() block {
	return block{
		Hash: d.genesis.EVMGenesisHash(), Number: 0, StateRoot: d.genesis.StateRoot(), PartitionRound: 0,
		Evidence: d.genesis.Evidence(),
	}
}

type nodeList [][]byte

func (l *nodeList) Put(_, v []byte) error { *l = append(*l, bytes.Clone(v)); return nil }
func (l *nodeList) Delete([]byte) error   { return nil }

func newTrie() *trie.Trie { return trie.NewEmpty(triedb.NewDatabase(rawdb.NewMemoryDatabase(), nil)) }

func word(v uint64) common.Hash { return common.BigToHash(new(big.Int).SetUint64(v)) }

// executed builds the block that executes partition round `round` on parent, as EVM block number
// parent.Number+1, with the registry left finalized for that round.
func (d *deployment) executed(t testing.TB, parent block, round, rootRound uint64) block {
	words := d.genesis.Storage()
	named := func(s string) common.Hash { return crypto.Keccak256Hash([]byte(s)) }
	for k, v := range map[string]common.Hash{
		"clock.rootRound": word(rootRound), "origin.rootEpoch": word(1), "origin.timestamp": word(1_700_000_000 + rootRound),
		"origin.treeRoot": named(fmt.Sprint("U", rootRound)), "origin.identity": named(fmt.Sprint("O", rootRound)),
		"origin.trHash": named(fmt.Sprint("T", rootRound)), "round.authorized": word(round),
		"input.commitment": named(fmt.Sprint("X", round)), "certified.round": word(parent.PartitionRound),
		"certified.stateHash": parent.StateRoot, "outcomes.round": word(round), "outcomes.commitment": named(fmt.Sprint("R", round)),
	} {
		words[k] = v
	}

	storage := newTrie()
	paths := make([][]byte, registryproof.FieldCount)
	for i, name := range registryproof.SlotNames {
		key := registryproof.SlotKey(i)
		paths[i] = crypto.Keccak256(key[:])
		if w := words[name]; w != (common.Hash{}) {
			v, err := rlp.EncodeToBytes(common.TrimLeftZeroes(w[:]))
			require.NoError(t, err)
			require.NoError(t, storage.Update(paths[i], v))
		}
	}
	account, err := rlp.EncodeToBytes(&types.StateAccount{Balance: new(uint256.Int), Root: storage.Hash(), CodeHash: d.codeHash.Bytes()})
	require.NoError(t, err)
	state := newTrie()
	accountPath := crypto.Keccak256(registryproof.RegistryAddress[:])
	require.NoError(t, state.Update(accountPath, account))

	withdrawals, beacon := types.EmptyWithdrawalsHash, common.Hash{}
	zero := uint64(0)
	h := &types.Header{
		ParentHash: parent.Hash, UncleHash: types.EmptyUncleHash, Root: state.Hash(), TxHash: types.EmptyTxsHash,
		ReceiptHash: types.EmptyReceiptsHash, Difficulty: new(big.Int), Number: new(big.Int).SetUint64(parent.Number + 1),
		GasLimit: 30_000_000, Time: 1_700_000_000 + parent.Number + 1, Extra: named(fmt.Sprint("X", round)).Bytes(),
		BaseFee: big.NewInt(7), WithdrawalsHash: &withdrawals, BlobGasUsed: &zero, ExcessBlobGas: &zero, ParentBeaconRoot: &beacon,
	}
	header, err := rlp.EncodeToBytes(h)
	require.NoError(t, err)

	var accountProof nodeList
	require.NoError(t, state.Prove(accountPath, &accountProof))
	ev := registryproof.Evidence{Header: header, AccountProof: accountProof, StorageProofs: make([][][]byte, registryproof.FieldCount)}
	for i := range paths {
		var p nodeList
		require.NoError(t, storage.Prove(paths[i], &p))
		ev.StorageProofs[i] = p
	}
	return block{Hash: h.Hash(), Parent: parent.Hash, Number: parent.Number + 1, StateRoot: h.Root, PartitionRound: round, Evidence: ev}
}

// chain returns genesis followed by n executed blocks for partition rounds 1..n (root rounds 5, 6, ...).
func (d *deployment) chain(t testing.TB, n int) []block {
	out := []block{d.genesisBlock()}
	for i := 1; i <= n; i++ {
		out = append(out, d.executed(t, out[i-1], uint64(i), uint64(4+i)))
	}
	return out
}

/*
fakeRPC is an in-process registrywitness.Caller serving the evidence of known blocks by hash, with the
pinned reth's measured refusals: a block past the proof window is -32602, an unknown block is -32001
(registrywitness/testdata/reth-proof-window.json).
*/
type fakeRPC struct {
	mu      sync.Mutex
	blocks  map[common.Hash]block
	expired map[common.Hash]bool
}

func newFakeRPC(blocks ...block) *fakeRPC {
	r := &fakeRPC{blocks: map[common.Hash]block{}, expired: map[common.Hash]bool{}}
	for _, b := range blocks {
		r.blocks[b.Hash] = b
	}
	return r
}

func (r *fakeRPC) expire(h common.Hash) { r.mu.Lock(); r.expired[h] = true; r.mu.Unlock() }

func (r *fakeRPC) Call(_ context.Context, method string, params []any) (json.RawMessage, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	var hash common.Hash
	switch method {
	case "debug_getRawHeader":
		hash = params[0].(common.Hash)
	case "eth_getProof":
		hash = params[2].(map[string]any)["blockHash"].(common.Hash)
	default:
		return nil, &registrywitness.RPCError{Code: -32601, Message: "method not found"}
	}
	b, ok := r.blocks[hash]
	if !ok {
		return nil, &registrywitness.RPCError{Code: -32001, Message: "block not found: hash " + hash.Hex()}
	}
	if method == "debug_getRawHeader" {
		return json.Marshal(hexutil.Encode(b.Evidence.Header))
	}
	if r.expired[hash] {
		return nil, &registrywitness.RPCError{Code: -32602, Message: "distance to target block exceeds maximum proof window"}
	}
	hexNodes := func(nodes [][]byte) []string {
		out := make([]string, len(nodes))
		for i, n := range nodes {
			out[i] = hexutil.Encode(n)
		}
		return out
	}
	storage := make([]map[string]any, registryproof.FieldCount)
	for i := range storage {
		storage[i] = map[string]any{"key": registryproof.SlotKey(i).Hex(), "value": "0x0", "proof": hexNodes(b.Evidence.StorageProofs[i])}
	}
	return json.Marshal(map[string]any{"address": registryproof.RegistryAddress.Hex(), "accountProof": hexNodes(b.Evidence.AccountProof), "storageProof": storage})
}

var errPayloadUnavailable = errors.New("model executor: payload unavailable")

// fakeExecutor holds payloads by hash and a committed head. Commit makes a held payload the head; a missing
// payload is the StatusSyncing case of shardnode.Executor.
type fakeExecutor struct {
	head     block
	payloads map[common.Hash]block
}

func newFakeExecutor(genesis block, payloads ...block) *fakeExecutor {
	e := &fakeExecutor{head: genesis, payloads: map[common.Hash]block{genesis.Hash: genesis}}
	for _, p := range payloads {
		e.payloads[p.Hash] = p
	}
	return e
}

func (e *fakeExecutor) commit(h common.Hash) error {
	b, ok := e.payloads[h]
	if !ok {
		return errPayloadUnavailable
	}
	e.head = b
	return nil
}

func TestFixtureChainVerifiesAsFinalizedParents(t *testing.T) {
	d := newDeployment(t, 3)
	chain := d.chain(t, 3)
	for i, b := range chain {
		s, err := registryproof.Verify(d.ctx, b.Hash, b.Evidence)
		require.NoError(t, err, "block %d", i)
		require.Equal(t, b.Number, s.Number())
		require.Equal(t, b.PartitionRound, s.Fields().RoundAuthorized)
		if i > 0 {
			require.Equal(t, chain[i-1].Hash, b.Parent)
		}
	}
}
