/*
Package certifiedchain builds a SealRegistry deployment and a chain of certified EVM blocks for tests: a
deployment generated by registrygenesis, blocks whose registry storage is finalized for their rounds in real
state tries, and unicity certificates really signed over the full shard configuration with a fixed key, so a
child process builds certificates a parent's trust base accepts.

It imports no store or node package, so their own package-internal tests can use it.
*/
package certifiedchain

import (
	"bytes"
	"fmt"
	"math/big"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/rawdb"
	ethtypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/trie"
	"github.com/ethereum/go-ethereum/triedb"
	"github.com/holiman/uint256"
	"github.com/stretchr/testify/require"
	abcrypto "github.com/unicitynetwork/bft-go-base/crypto"
	"github.com/unicitynetwork/bft-go-base/types"

	testcertificates "github.com/unicitynetwork/bft-core/internal/testutils/certificates"
	testtrustbase "github.com/unicitynetwork/bft-core/internal/testutils/trustbase"
	"github.com/unicitynetwork/bft-core/network/protocol/certification"
	"github.com/unicitynetwork/bft-core/registrygenesis"
	"github.com/unicitynetwork/bft-core/registryproof"
)

// Key is the fixed root signing key.
var Key = bytes.Repeat([]byte{0x42}, 32)

// Block is one EVM block of the chain with witness(B).
type Block struct {
	Hash      common.Hash
	Number    uint64
	StateRoot common.Hash
	Round     uint64
	Evidence  registryproof.Evidence
}

// Chain is a deployment and its certified blocks. Blocks[0] is the EVM genesis.
type Chain struct {
	// Layout is the registry layout of the deployment: 1 (zero) or 2, the assignment-aware registry.
	Layout    uint64
	T         *testing.T
	Signer    abcrypto.Signer
	TrustBase *types.RootTrustBaseV1
	Pins      registrygenesis.Pins
	Genesis   *registrygenesis.Genesis
	Full      *types.PartitionDescriptionRecord
	Blocks    []Block
}

// Config is the base shard configuration of the deployment for network: partition 8, chain id 1337,
// shard epoch 0, one validator.
func Config(network types.NetworkID) *types.PartitionDescriptionRecord {
	return &types.PartitionDescriptionRecord{
		Version: 1, NetworkID: network, PartitionID: 8, T2Timeout: 5 * time.Second,
		PartitionParams: map[string]string{registrygenesis.ChainIDParam: "1337"}, Epoch: 0,
		Validators: []*types.NodeInfo{{NodeID: "validator-1", SigKey: append([]byte{0x02}, make([]byte, 32)...), Stake: 1}},
	}
}

// New generates the deployment for network, at root epoch 1, and blocks executed blocks after genesis.
func New(t *testing.T, network types.NetworkID, blocks int) *Chain {
	return newChain(t, network, blocks, 1)
}

// NewV2 is New for the assignment-aware sealRegistry/v2 deployment.
func NewV2(t *testing.T, network types.NetworkID, blocks int) *Chain {
	return newChain(t, network, blocks, 2)
}

func newChain(t *testing.T, network types.NetworkID, blocks int, layout uint64) *Chain {
	signer, err := abcrypto.NewInMemorySecp256K1SignerFromKey(Key)
	require.NoError(t, err)
	tb, ok := testtrustbase.NewTrustBase(t, signer).(*types.RootTrustBaseV1)
	require.True(t, ok)

	var art registrygenesis.Artifact
	if layout == 2 {
		art, err = registrygenesis.PinnedArtifactV2()
	} else {
		art, err = registrygenesis.PinnedArtifact()
	}
	require.NoError(t, err)
	pins := registrygenesis.Pins{RootEpoch: 1, RegistryCodeHash: art.CodeHash, SystemAddress: registrygenesis.SystemAddress, RegistryAddress: registryproof.RegistryAddress}
	g, err := registrygenesis.Generate(Config(network), pins, art, registrygenesis.DefaultEVMParams)
	require.NoError(t, err)
	full, err := g.FullConfig()
	require.NoError(t, err)

	c := &Chain{T: t, Signer: signer, TrustBase: tb, Pins: pins, Genesis: g, Full: full}
	if layout == 2 {
		c.Layout = 2
	} else {
		c.Layout = 0
	}
	c.Blocks = []Block{{Hash: g.EVMGenesisHash(), Number: 0, StateRoot: g.StateRoot(), Round: 0, Evidence: g.Evidence()}}
	for i := 1; i <= blocks; i++ {
		c.Blocks = append(c.Blocks, c.Executed(c.Blocks[i-1], uint64(i), uint64(4+i)))
	}
	return c
}

type nodeList [][]byte

func (l *nodeList) Put(_, v []byte) error { *l = append(*l, bytes.Clone(v)); return nil }
func (l *nodeList) Delete([]byte) error   { return nil }

func newTrie() *trie.Trie { return trie.NewEmpty(triedb.NewDatabase(rawdb.NewMemoryDatabase(), nil)) }

func word(v uint64) common.Hash { return common.BigToHash(new(big.Int).SetUint64(v)) }

// Executed builds the block executing partition round `round` on parent, with registry storage as a
// successful open and finalize leave it (#153 §6.2, §6.3).
func (c *Chain) Executed(parent Block, round, rootRound uint64) Block {
	return c.ExecutedWith(parent, round, rootRound, crypto.Keccak256Hash([]byte(fmt.Sprint("X", round))).Bytes())
}

// ExecutedWith is Executed with the header's extraData given, so a test can build another block for the same
// round, parent and state.
func (c *Chain) ExecutedWith(parent Block, round, rootRound uint64, extra []byte) Block {
	return c.ExecutedState(parent, round, rootRound, extra, nil)
}

// ExecutedState is ExecutedWith with further registry words set, so a test can show the registry as it stands
// after an acknowledgement: its assignment words, cursor and transition record.
func (c *Chain) ExecutedState(parent Block, round, rootRound uint64, extra []byte, more map[string]common.Hash) Block {
	t := c.T
	words := c.Genesis.Storage()
	named := func(s string) common.Hash { return crypto.Keccak256Hash([]byte(s)) }
	for k, v := range map[string]common.Hash{
		"clock.rootRound": word(rootRound), "origin.rootEpoch": word(1), "origin.timestamp": word(1_700_000_000 + rootRound),
		"origin.treeRoot": named(fmt.Sprint("U", rootRound)), "origin.identity": named(fmt.Sprint("O", rootRound)),
		"origin.trHash": named(fmt.Sprint("T", rootRound)), "round.authorized": word(round),
		"input.commitment": named(fmt.Sprint("X", round)), "certified.round": word(parent.Round),
		"certified.stateHash": parent.StateRoot, "outcomes.round": word(round), "outcomes.commitment": named(fmt.Sprint("R", round)),
	} {
		words[k] = v
	}
	for k, v := range more {
		words[k] = v
	}
	names, err := registryproof.SlotNamesFor(c.Layout)
	require.NoError(t, err)
	storage := newTrie()
	paths := make([][]byte, len(names))
	for i, name := range names {
		key, err := registryproof.SlotKeyFor(c.Layout, i)
		require.NoError(t, err)
		paths[i] = crypto.Keccak256(key[:])
		if w := words[name]; w != (common.Hash{}) {
			v, err := rlp.EncodeToBytes(common.TrimLeftZeroes(w[:]))
			require.NoError(t, err)
			require.NoError(t, storage.Update(paths[i], v))
		}
	}
	account, err := rlp.EncodeToBytes(&ethtypes.StateAccount{Balance: new(uint256.Int), Root: storage.Hash(), CodeHash: c.Pins.RegistryCodeHash.Bytes()})
	require.NoError(t, err)
	state := newTrie()
	accountPath := crypto.Keccak256(registryproof.RegistryAddress[:])
	require.NoError(t, state.Update(accountPath, account))

	withdrawals, beacon, zero := ethtypes.EmptyWithdrawalsHash, common.Hash{}, uint64(0)
	h := &ethtypes.Header{
		ParentHash: parent.Hash, UncleHash: ethtypes.EmptyUncleHash, Root: state.Hash(), TxHash: ethtypes.EmptyTxsHash,
		ReceiptHash: ethtypes.EmptyReceiptsHash, Difficulty: new(big.Int), Number: new(big.Int).SetUint64(parent.Number + 1),
		GasLimit: 30_000_000, Time: 1_700_000_000 + parent.Number + 1, Extra: bytes.Clone(extra),
		BaseFee: big.NewInt(7), WithdrawalsHash: &withdrawals, BlobGasUsed: &zero, ExcessBlobGas: &zero, ParentBeaconRoot: &beacon,
	}
	header, err := rlp.EncodeToBytes(h)
	require.NoError(t, err)
	var accountProof nodeList
	require.NoError(t, state.Prove(accountPath, &accountProof))
	ev := registryproof.Evidence{Header: header, AccountProof: accountProof, StorageProofs: make([][][]byte, len(names))}
	for i := range paths {
		var p nodeList
		require.NoError(t, storage.Prove(paths[i], &p))
		ev.StorageProofs[i] = p
	}
	return Block{Hash: h.Hash(), Number: parent.Number + 1, StateRoot: h.Root, Round: round, Evidence: ev}
}

// InputRecord is the certified input record for block i: genesis history for block 0 (no block, state and
// previous state at the genesis state, #153 §7.3 E2), and a block-naming record for later blocks.
func (c *Chain) InputRecord(i int) *types.InputRecord {
	b := c.Blocks[i]
	ir := &types.InputRecord{
		Version: 1, RoundNumber: b.Round, Epoch: 0, Hash: b.StateRoot.Bytes(), SummaryValue: []byte{}, Timestamp: 1_700_000_000 + b.Round,
	}
	if i == 0 {
		ir.PreviousHash = b.StateRoot.Bytes()
	} else {
		ir.PreviousHash = c.Blocks[i-1].StateRoot.Bytes()
		ir.BlockHash = b.Hash.Bytes()
	}
	return ir
}

// Technical is the technical record assigning round+1.
func Technical(round uint64) *certification.TechnicalRecord {
	return &certification.TechnicalRecord{Round: round + 1, Epoch: 0, Leader: "leader", StatHash: bytes.Repeat([]byte{0xa1}, 32), FeeHash: bytes.Repeat([]byte{0xa2}, 32)}
}

// Certify signs a certificate for ir and tr over the full shard configuration.
func (c *Chain) Certify(signer abcrypto.Signer, ir *types.InputRecord, tr *certification.TechnicalRecord, rootRound uint64) *types.UnicityCertificate {
	return c.CertifyFor(c.Full, signer, ir, tr, rootRound)
}

// CertifyFor signs a certificate over the given shard configuration: the genesis one, or the configuration of
// an installed EVM assignment.
func (c *Chain) CertifyFor(full *types.PartitionDescriptionRecord, signer abcrypto.Signer, ir *types.InputRecord, tr *certification.TechnicalRecord, rootRound uint64) *types.UnicityCertificate {
	trHash, err := tr.Hash()
	require.NoError(c.T, err)
	uc := testcertificates.CreateUnicityCertificate(c.T, signer, ir, full, rootRound, bytes.Repeat([]byte{0xb0}, 32), trHash)
	require.NotNil(c.T, uc)
	return uc
}

// Certificate is the certificate and technical record for block i, signed by the chain's key at root round
// 4 + the block's round.
func (c *Chain) Certificate(i int) (*types.UnicityCertificate, *certification.TechnicalRecord) {
	tr := Technical(c.Blocks[i].Round)
	return c.Certify(c.Signer, c.InputRecord(i), tr, 4+c.Blocks[i].Round), tr
}
